// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_0_DebayerRandBatG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        height,
        width,
        bayerPhase_c_dout,
        bayerPhase_c_num_data_valid,
        bayerPhase_c_fifo_cap,
        bayerPhase_c_empty_n,
        bayerPhase_c_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] imgRB_dout;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [47:0] imgRgb_din;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [11:0] height;
input  [11:0] width;
input  [15:0] bayerPhase_c_dout;
input  [2:0] bayerPhase_c_num_data_valid;
input  [2:0] bayerPhase_c_fifo_cap;
input   bayerPhase_c_empty_n;
output   bayerPhase_c_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgRB_read;
reg imgRgb_write;
reg bayerPhase_c_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bayerPhase_c_blk_n;
reg    ap_block_state1;
wire   [11:0] loopHeight_fu_242_p2;
reg   [11:0] loopHeight_reg_568;
reg   [14:0] trunc_ln870_1_i_reg_573;
wire   [14:0] zext_ln871_fu_262_p1;
reg   [14:0] zext_ln871_reg_578;
wire   [10:0] add_ln878_1_fu_282_p2;
reg   [10:0] add_ln878_1_reg_583;
wire   [14:0] xor309_1_cast_i_fu_294_p1;
reg   [14:0] xor309_1_cast_i_reg_588;
reg   [7:0] p_0_0_0_0_01166_11784_lcssa1845_i_load_reg_596;
wire    ap_CS_fsm_state2;
reg   [7:0] p_0_1_0_0_01167_11787_lcssa1847_i_load_reg_601;
reg   [7:0] p_0_2_0_0_01168_11790_lcssa1849_i_load_reg_606;
reg   [7:0] pixWindow_load_reg_611;
reg   [7:0] pixWindow_151_load_reg_616;
reg   [7:0] pixWindow_152_load_reg_621;
reg   [7:0] pixWindow_153_load_reg_626;
reg   [7:0] pixWindow_154_load_reg_631;
reg   [7:0] pixWindow_155_load_reg_636;
reg   [7:0] pixWindow_156_load_reg_641;
reg   [7:0] pixWindow_157_load_reg_646;
reg   [7:0] pixWindow_158_load_reg_651;
reg   [7:0] pixWindow_159_load_reg_656;
reg   [7:0] pixWindow_160_load_reg_661;
reg   [7:0] pixWindow_161_load_reg_666;
reg   [7:0] pixWindow_162_load_reg_671;
reg   [7:0] pixWindow_163_load_reg_676;
reg   [7:0] pixWindow_164_load_reg_681;
reg   [7:0] pixWindow_165_load_reg_686;
reg   [7:0] pixWindow_166_load_reg_691;
reg   [7:0] pixWindow_167_load_reg_696;
wire   [0:0] cmp478_i_fu_399_p2;
reg   [0:0] cmp478_i_reg_701;
wire   [0:0] cmp59_i_fu_405_p2;
reg   [0:0] cmp59_i_reg_706;
wire   [0:0] cmp310_i_fu_410_p2;
reg   [0:0] cmp310_i_reg_711;
wire   [0:0] cmp310_1_i_fu_415_p2;
reg   [0:0] cmp310_1_i_reg_716;
wire   [47:0] lineBuffer_q1;
wire   [47:0] lineBuffer_2_q1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_done;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_idle;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_ready;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRB_read;
wire   [47:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_din;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_write;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_we0;
wire   [47:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce1;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_we0;
wire   [47:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce1;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out_ap_vld;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out_ap_vld;
reg    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] pixWindow_167_fu_154;
reg   [7:0] pixWindow_166_fu_150;
reg   [7:0] pixWindow_165_fu_146;
reg   [7:0] pixWindow_164_fu_142;
reg   [7:0] pixWindow_163_fu_138;
reg   [7:0] pixWindow_162_fu_134;
reg   [7:0] pixWindow_161_fu_130;
reg   [7:0] pixWindow_160_fu_126;
reg   [7:0] pixWindow_159_fu_122;
reg   [7:0] pixWindow_158_fu_118;
reg   [7:0] pixWindow_157_fu_114;
reg   [7:0] pixWindow_156_fu_110;
reg   [7:0] pixWindow_155_fu_106;
reg   [7:0] pixWindow_154_fu_102;
reg   [7:0] pixWindow_153_fu_98;
reg   [7:0] pixWindow_152_fu_94;
reg   [7:0] pixWindow_151_fu_90;
reg   [7:0] pixWindow_fu_86;
reg   [7:0] p_0_2_0_0_01168_11790_lcssa1849_i_fu_82;
reg   [7:0] p_0_1_0_0_01167_11787_lcssa1847_i_fu_78;
reg   [7:0] p_0_0_0_0_01166_11784_lcssa1845_i_fu_74;
reg   [11:0] y_fu_70;
wire   [11:0] y_6_fu_311_p2;
wire   [0:0] icmp_ln878_fu_306_p2;
wire   [0:0] x_phase_fu_248_p1;
wire   [11:0] add_ln878_fu_266_p2;
wire   [10:0] trunc_ln_i_fu_272_p4;
wire   [0:0] xor309_1_i_fu_288_p2;
wire   [0:0] trunc_ln878_fu_380_p1;
wire   [0:0] tmp_i_fu_384_p2;
wire   [14:0] tmp_cast_i_fu_390_p1;
wire   [14:0] xor_i_fu_394_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg = 1'b0;
#0 y_fu_70 = 12'd0;
end

system_v_demosaic_0_0_DebayerRandBatG_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 48 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce1),
    .q1(lineBuffer_q1)
);

system_v_demosaic_0_0_DebayerRandBatG_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 48 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce1),
    .q1(lineBuffer_2_q1)
);

system_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start),
    .ap_done(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_done),
    .ap_idle(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_idle),
    .ap_ready(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_num_data_valid(3'd0),
    .imgRB_fifo_cap(3'd0),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRB_read),
    .imgRgb_din(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_din),
    .imgRgb_num_data_valid(3'd0),
    .imgRgb_fifo_cap(3'd0),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_write),
    .pixWindow_94_i(pixWindow_167_load_reg_696),
    .pixWindow_93_i(pixWindow_166_load_reg_691),
    .pixWindow_92_i(pixWindow_165_load_reg_686),
    .pixWindow_91_i(pixWindow_164_load_reg_681),
    .pixWindow_90_i(pixWindow_163_load_reg_676),
    .pixWindow_89_i(pixWindow_162_load_reg_671),
    .pixWindow_88_i(pixWindow_161_load_reg_666),
    .pixWindow_87_i(pixWindow_160_load_reg_661),
    .pixWindow_86_i(pixWindow_159_load_reg_656),
    .pixWindow_85_i(pixWindow_158_load_reg_651),
    .pixWindow_84_i(pixWindow_157_load_reg_646),
    .pixWindow_83_i(pixWindow_156_load_reg_641),
    .pixWindow_82_i(pixWindow_155_load_reg_636),
    .pixWindow_81_i(pixWindow_154_load_reg_631),
    .pixWindow_80_i(pixWindow_153_load_reg_626),
    .pixWindow_79_i(pixWindow_152_load_reg_621),
    .pixWindow_78_i(pixWindow_151_load_reg_616),
    .pixWindow_i(pixWindow_load_reg_611),
    .p_0_2_0_0_01168_11790_lcssa1849_i(p_0_2_0_0_01168_11790_lcssa1849_i_load_reg_606),
    .p_0_1_0_0_01167_11787_lcssa1847_i(p_0_1_0_0_01167_11787_lcssa1847_i_load_reg_601),
    .p_0_0_0_0_01166_11784_lcssa1845_i(p_0_0_0_0_01166_11784_lcssa1845_i_load_reg_596),
    .add_ln878_1_i(add_ln878_1_reg_583),
    .cmp310_i(cmp310_i_reg_711),
    .cmp310_1_i(cmp310_1_i_reg_716),
    .cmp478_i(cmp478_i_reg_701),
    .lineBuffer_1_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address0),
    .lineBuffer_1_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce0),
    .lineBuffer_1_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_we0),
    .lineBuffer_1_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_d0),
    .lineBuffer_1_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_address1),
    .lineBuffer_1_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_1_i_ce1),
    .lineBuffer_1_i_q1(lineBuffer_2_q1),
    .lineBuffer_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address0),
    .lineBuffer_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce0),
    .lineBuffer_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_we0),
    .lineBuffer_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_d0),
    .lineBuffer_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_address1),
    .lineBuffer_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_lineBuffer_i_ce1),
    .lineBuffer_i_q1(lineBuffer_q1),
    .empty(width),
    .cmp59_i(cmp59_i_reg_706),
    .pixWindow_112_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out),
    .pixWindow_112_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out_ap_vld),
    .pixWindow_111_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out),
    .pixWindow_111_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out_ap_vld),
    .pixWindow_110_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out),
    .pixWindow_110_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out_ap_vld),
    .pixWindow_109_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out),
    .pixWindow_109_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out_ap_vld),
    .pixWindow_108_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out),
    .pixWindow_108_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out_ap_vld),
    .pixWindow_107_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out),
    .pixWindow_107_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out_ap_vld),
    .pixWindow_106_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out),
    .pixWindow_106_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out_ap_vld),
    .pixWindow_105_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out),
    .pixWindow_105_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out_ap_vld),
    .pixWindow_104_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out),
    .pixWindow_104_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out_ap_vld),
    .pixWindow_103_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out),
    .pixWindow_103_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out_ap_vld),
    .pixWindow_102_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out),
    .pixWindow_102_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out_ap_vld),
    .pixWindow_101_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out),
    .pixWindow_101_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out_ap_vld),
    .pixWindow_100_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out),
    .pixWindow_100_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out_ap_vld),
    .pixWindow_99_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out),
    .pixWindow_99_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out_ap_vld),
    .pixWindow_98_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out),
    .pixWindow_98_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out_ap_vld),
    .pixWindow_97_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out),
    .pixWindow_97_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out_ap_vld),
    .pixWindow_96_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out),
    .pixWindow_96_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out_ap_vld),
    .pixWindow_95_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out),
    .pixWindow_95_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out_ap_vld),
    .p_0_2_0_0_01168_11792_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out),
    .p_0_2_0_0_01168_11792_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out_ap_vld),
    .p_0_1_0_0_01167_11789_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out),
    .p_0_1_0_0_01167_11789_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out_ap_vld),
    .p_0_0_0_0_01166_11786_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out),
    .p_0_0_0_0_01166_11786_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln878_fu_306_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_ready == 1'b1)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_70 <= 12'd0;
    end else if (((icmp_ln878_fu_306_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_70 <= y_6_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln878_1_reg_583 <= add_ln878_1_fu_282_p2;
        loopHeight_reg_568 <= loopHeight_fu_242_p2;
        trunc_ln870_1_i_reg_573 <= {{bayerPhase_c_dout[15:1]}};
        xor309_1_cast_i_reg_588[0] <= xor309_1_cast_i_fu_294_p1[0];
        zext_ln871_reg_578[0] <= zext_ln871_fu_262_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp310_1_i_reg_716 <= cmp310_1_i_fu_415_p2;
        cmp310_i_reg_711 <= cmp310_i_fu_410_p2;
        cmp478_i_reg_701 <= cmp478_i_fu_399_p2;
        cmp59_i_reg_706 <= cmp59_i_fu_405_p2;
        p_0_0_0_0_01166_11784_lcssa1845_i_load_reg_596 <= p_0_0_0_0_01166_11784_lcssa1845_i_fu_74;
        p_0_1_0_0_01167_11787_lcssa1847_i_load_reg_601 <= p_0_1_0_0_01167_11787_lcssa1847_i_fu_78;
        p_0_2_0_0_01168_11790_lcssa1849_i_load_reg_606 <= p_0_2_0_0_01168_11790_lcssa1849_i_fu_82;
        pixWindow_151_load_reg_616 <= pixWindow_151_fu_90;
        pixWindow_152_load_reg_621 <= pixWindow_152_fu_94;
        pixWindow_153_load_reg_626 <= pixWindow_153_fu_98;
        pixWindow_154_load_reg_631 <= pixWindow_154_fu_102;
        pixWindow_155_load_reg_636 <= pixWindow_155_fu_106;
        pixWindow_156_load_reg_641 <= pixWindow_156_fu_110;
        pixWindow_157_load_reg_646 <= pixWindow_157_fu_114;
        pixWindow_158_load_reg_651 <= pixWindow_158_fu_118;
        pixWindow_159_load_reg_656 <= pixWindow_159_fu_122;
        pixWindow_160_load_reg_661 <= pixWindow_160_fu_126;
        pixWindow_161_load_reg_666 <= pixWindow_161_fu_130;
        pixWindow_162_load_reg_671 <= pixWindow_162_fu_134;
        pixWindow_163_load_reg_676 <= pixWindow_163_fu_138;
        pixWindow_164_load_reg_681 <= pixWindow_164_fu_142;
        pixWindow_165_load_reg_686 <= pixWindow_165_fu_146;
        pixWindow_166_load_reg_691 <= pixWindow_166_fu_150;
        pixWindow_167_load_reg_696 <= pixWindow_167_fu_154;
        pixWindow_load_reg_611 <= pixWindow_fu_86;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_01166_11784_lcssa1845_i_fu_74 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_0_0_0_01166_11786_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_01167_11787_lcssa1847_i_fu_78 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_1_0_0_01167_11789_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_01168_11790_lcssa1849_i_fu_82 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_p_0_2_0_0_01168_11792_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_151_fu_90 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_96_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_152_fu_94 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_97_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_153_fu_98 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_98_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_154_fu_102 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_99_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_155_fu_106 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_100_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_156_fu_110 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_101_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_157_fu_114 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_102_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_158_fu_118 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_103_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_159_fu_122 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_104_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_160_fu_126 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_105_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_161_fu_130 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_106_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_162_fu_134 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_107_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_163_fu_138 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_108_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_164_fu_142 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_109_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_165_fu_146 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_110_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_166_fu_150 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_111_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_167_fu_154 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_112_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixWindow_fu_86 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_pixWindow_95_i_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_fu_306_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_fu_306_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_empty_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_read = 1'b1;
    end else begin
        bayerPhase_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRB_read = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRB_read;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRgb_write = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_write;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln878_fu_306_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln878_1_fu_282_p2 = (trunc_ln_i_fu_272_p4 + 11'd1);

assign add_ln878_fu_266_p2 = (width + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp310_1_i_fu_415_p2 = ((xor_i_fu_394_p2 == xor309_1_cast_i_reg_588) ? 1'b1 : 1'b0);

assign cmp310_i_fu_410_p2 = ((xor_i_fu_394_p2 == zext_ln871_reg_578) ? 1'b1 : 1'b0);

assign cmp478_i_fu_399_p2 = ((y_fu_70 != 12'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_405_p2 = ((y_fu_70 < height) ? 1'b1 : 1'b0);

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_ap_start_reg;

assign icmp_ln878_fu_306_p2 = ((y_fu_70 == loopHeight_reg_568) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_184_imgRgb_din;

assign loopHeight_fu_242_p2 = (height + 12'd1);

assign tmp_cast_i_fu_390_p1 = tmp_i_fu_384_p2;

assign tmp_i_fu_384_p2 = (trunc_ln878_fu_380_p1 ^ 1'd1);

assign trunc_ln878_fu_380_p1 = y_fu_70[0:0];

assign trunc_ln_i_fu_272_p4 = {{add_ln878_fu_266_p2[11:1]}};

assign x_phase_fu_248_p1 = bayerPhase_c_dout[0:0];

assign xor309_1_cast_i_fu_294_p1 = xor309_1_i_fu_288_p2;

assign xor309_1_i_fu_288_p2 = (x_phase_fu_248_p1 ^ 1'd1);

assign xor_i_fu_394_p2 = (trunc_ln870_1_i_reg_573 ^ tmp_cast_i_fu_390_p1);

assign y_6_fu_311_p2 = (y_fu_70 + 12'd1);

assign zext_ln871_fu_262_p1 = x_phase_fu_248_p1;

always @ (posedge ap_clk) begin
    zext_ln871_reg_578[14:1] <= 14'b00000000000000;
    xor309_1_cast_i_reg_588[14:1] <= 14'b00000000000000;
end

endmodule //system_v_demosaic_0_0_DebayerRandBatG
