// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_0_ZipperRemoval (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgRgb_dout,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_empty_n,
        imgRgb_read,
        imgUnzip_din,
        imgUnzip_num_data_valid,
        imgUnzip_fifo_cap,
        imgUnzip_full_n,
        imgUnzip_write,
        height,
        width
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] imgRgb_dout;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
input   imgRgb_empty_n;
output   imgRgb_read;
output  [47:0] imgUnzip_din;
input  [2:0] imgUnzip_num_data_valid;
input  [2:0] imgUnzip_fifo_cap;
input   imgUnzip_full_n;
output   imgUnzip_write;
input  [15:0] height;
input  [15:0] width;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgRgb_read;
reg imgUnzip_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ap_block_state1;
wire   [16:0] loopWidth_fu_151_p2;
reg   [16:0] loopWidth_reg_358;
reg   [7:0] p_0_0_0479657_lcssa670713_load_reg_366;
wire    ap_CS_fsm_state2;
reg   [7:0] p_0_0_0478653_lcssa672715_load_reg_371;
reg   [7:0] p_0_0_0477655_lcssa674717_load_reg_376;
reg   [7:0] conv2_i_i_1_lcssa719_load_reg_381;
reg   [7:0] p_0_0_0479_1663_lcssa677721_load_reg_386;
reg   [7:0] p_0_0_0478_1659_lcssa680722_load_reg_391;
reg   [7:0] p_0_0_0477_1661_lcssa683724_load_reg_396;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_done;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_idle;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_ready;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgRgb_read;
wire   [47:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_din;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_write;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o_ap_vld;
wire   [7:0] grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o;
wire    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o_ap_vld;
reg    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] p_0_0_0477_1661_lcssa683724_fu_102;
reg   [7:0] p_0_0_0478_1659_lcssa680722_fu_98;
reg   [7:0] p_0_0_0479_1663_lcssa677721_fu_94;
reg   [7:0] conv2_i_i_1_lcssa719_fu_90;
reg   [7:0] p_0_0_0477655_lcssa674717_fu_86;
reg   [7:0] p_0_0_0478653_lcssa672715_fu_82;
reg   [7:0] p_0_0_0479657_lcssa670713_fu_78;
reg   [7:0] conv2_i_i_lcssa711_fu_74;
reg   [7:0] p_0_0_0480_3_lcssa709_fu_70;
reg   [7:0] p_0_0_0481_3_lcssa707_fu_66;
reg   [7:0] p_0_0_0482_3_lcssa705_fu_62;
reg   [7:0] p_0_0_0483_3_lcssa703_fu_58;
reg   [15:0] y_fu_54;
wire   [15:0] y_2_fu_230_p2;
wire   [0:0] icmp_ln1099_fu_225_p2;
wire   [16:0] zext_ln1085_fu_147_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg = 1'b0;
#0 p_0_0_0477_1661_lcssa683724_fu_102 = 8'd0;
#0 p_0_0_0478_1659_lcssa680722_fu_98 = 8'd0;
#0 p_0_0_0479_1663_lcssa677721_fu_94 = 8'd0;
#0 conv2_i_i_1_lcssa719_fu_90 = 8'd0;
#0 p_0_0_0477655_lcssa674717_fu_86 = 8'd0;
#0 p_0_0_0478653_lcssa672715_fu_82 = 8'd0;
#0 p_0_0_0479657_lcssa670713_fu_78 = 8'd0;
#0 conv2_i_i_lcssa711_fu_74 = 8'd0;
#0 p_0_0_0480_3_lcssa709_fu_70 = 8'd0;
#0 p_0_0_0481_3_lcssa707_fu_66 = 8'd0;
#0 p_0_0_0482_3_lcssa705_fu_62 = 8'd0;
#0 p_0_0_0483_3_lcssa703_fu_58 = 8'd0;
#0 y_fu_54 = 16'd0;
end

system_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2 grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start),
    .ap_done(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_done),
    .ap_idle(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_idle),
    .ap_ready(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_ready),
    .imgRgb_dout(imgRgb_dout),
    .imgRgb_num_data_valid(3'd0),
    .imgRgb_fifo_cap(3'd0),
    .imgRgb_empty_n(imgRgb_empty_n),
    .imgRgb_read(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgRgb_read),
    .imgUnzip_din(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_din),
    .imgUnzip_num_data_valid(3'd0),
    .imgUnzip_fifo_cap(3'd0),
    .imgUnzip_full_n(imgUnzip_full_n),
    .imgUnzip_write(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_write),
    .p_0_0_0477_1661_lcssa683724(p_0_0_0477_1661_lcssa683724_load_reg_396),
    .p_0_0_0478_1659_lcssa680722(p_0_0_0478_1659_lcssa680722_load_reg_391),
    .p_0_0_0479_1663_lcssa677721(p_0_0_0479_1663_lcssa677721_load_reg_386),
    .conv2_i_i_1_lcssa719(conv2_i_i_1_lcssa719_load_reg_381),
    .p_0_0_0477655_lcssa674717(p_0_0_0477655_lcssa674717_load_reg_376),
    .p_0_0_0478653_lcssa672715(p_0_0_0478653_lcssa672715_load_reg_371),
    .p_0_0_0479657_lcssa670713(p_0_0_0479657_lcssa670713_load_reg_366),
    .loopWidth(loopWidth_reg_358),
    .zext_ln1085(width),
    .p_0_0_0480_3682_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out),
    .p_0_0_0480_3682_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out_ap_vld),
    .p_0_0_0481_3679_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out),
    .p_0_0_0481_3679_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out_ap_vld),
    .p_0_0_0482_3676_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out),
    .p_0_0_0482_3676_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out_ap_vld),
    .p_0_0_0483_3675_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out),
    .p_0_0_0483_3675_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out_ap_vld),
    .p_0_0_0477655673_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out),
    .p_0_0_0477655673_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out_ap_vld),
    .p_0_0_0478653671_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out),
    .p_0_0_0478653671_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out_ap_vld),
    .p_0_0_0479657669_out(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out),
    .p_0_0_0479657669_out_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out_ap_vld),
    .conv2_i_i668_out_i(conv2_i_i_lcssa711_fu_74),
    .conv2_i_i668_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o),
    .conv2_i_i668_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o_ap_vld),
    .p_0_0_0480_3667_out_i(p_0_0_0480_3_lcssa709_fu_70),
    .p_0_0_0480_3667_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o),
    .p_0_0_0480_3667_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o_ap_vld),
    .p_0_0_0481_3666_out_i(p_0_0_0481_3_lcssa707_fu_66),
    .p_0_0_0481_3666_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o),
    .p_0_0_0481_3666_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o_ap_vld),
    .p_0_0_0482_3665_out_i(p_0_0_0482_3_lcssa705_fu_62),
    .p_0_0_0482_3665_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o),
    .p_0_0_0482_3665_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o_ap_vld),
    .p_0_0_0483_3664_out_i(p_0_0_0483_3_lcssa703_fu_58),
    .p_0_0_0483_3664_out_o(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o),
    .p_0_0_0483_3664_out_o_ap_vld(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_225_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_ready == 1'b1)) begin
            grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        conv2_i_i_1_lcssa719_fu_90 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out_ap_vld == 1'b1))) begin
        conv2_i_i_1_lcssa719_fu_90 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3675_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        conv2_i_i_lcssa711_fu_74 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o_ap_vld == 1'b1))) begin
        conv2_i_i_lcssa711_fu_74 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_conv2_i_i668_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0477655_lcssa674717_fu_86 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out_ap_vld == 1'b1))) begin
        p_0_0_0477655_lcssa674717_fu_86 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0477655673_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0477_1661_lcssa683724_fu_102 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out_ap_vld == 1'b1))) begin
        p_0_0_0477_1661_lcssa683724_fu_102 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3682_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0478653_lcssa672715_fu_82 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out_ap_vld == 1'b1))) begin
        p_0_0_0478653_lcssa672715_fu_82 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0478653671_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0478_1659_lcssa680722_fu_98 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out_ap_vld == 1'b1))) begin
        p_0_0_0478_1659_lcssa680722_fu_98 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3679_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0479657_lcssa670713_fu_78 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out_ap_vld == 1'b1))) begin
        p_0_0_0479657_lcssa670713_fu_78 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0479657669_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0479_1663_lcssa677721_fu_94 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out_ap_vld == 1'b1))) begin
        p_0_0_0479_1663_lcssa677721_fu_94 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3676_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0480_3_lcssa709_fu_70 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o_ap_vld == 1'b1))) begin
        p_0_0_0480_3_lcssa709_fu_70 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0480_3667_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0481_3_lcssa707_fu_66 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o_ap_vld == 1'b1))) begin
        p_0_0_0481_3_lcssa707_fu_66 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0481_3666_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0482_3_lcssa705_fu_62 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o_ap_vld == 1'b1))) begin
        p_0_0_0482_3_lcssa705_fu_62 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0482_3665_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0483_3_lcssa703_fu_58 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o_ap_vld == 1'b1))) begin
        p_0_0_0483_3_lcssa703_fu_58 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_p_0_0_0483_3664_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_54 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_225_p2 == 1'd0))) begin
        y_fu_54 <= y_2_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv2_i_i_1_lcssa719_load_reg_381 <= conv2_i_i_1_lcssa719_fu_90;
        p_0_0_0477655_lcssa674717_load_reg_376 <= p_0_0_0477655_lcssa674717_fu_86;
        p_0_0_0477_1661_lcssa683724_load_reg_396 <= p_0_0_0477_1661_lcssa683724_fu_102;
        p_0_0_0478653_lcssa672715_load_reg_371 <= p_0_0_0478653_lcssa672715_fu_82;
        p_0_0_0478_1659_lcssa680722_load_reg_391 <= p_0_0_0478_1659_lcssa680722_fu_98;
        p_0_0_0479657_lcssa670713_load_reg_366 <= p_0_0_0479657_lcssa670713_fu_78;
        p_0_0_0479_1663_lcssa677721_load_reg_386 <= p_0_0_0479_1663_lcssa677721_fu_94;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        loopWidth_reg_358 <= loopWidth_fu_151_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_225_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRgb_read = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgRgb_read;
    end else begin
        imgRgb_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgUnzip_write = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_write;
    end else begin
        imgUnzip_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_225_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1099_fu_225_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_ap_start_reg;

assign icmp_ln1099_fu_225_p2 = ((y_fu_54 == height) ? 1'b1 : 1'b0);

assign imgUnzip_din = grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_118_imgUnzip_din;

assign loopWidth_fu_151_p2 = (zext_ln1085_fu_147_p1 + 17'd1);

assign start_out = real_start;

assign y_2_fu_230_p2 = (y_fu_54 + 16'd1);

assign zext_ln1085_fu_147_p1 = width;

endmodule //system_v_demosaic_0_0_ZipperRemoval
