// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_0_DebayerG (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgBayer_dout,
        imgBayer_num_data_valid,
        imgBayer_fifo_cap,
        imgBayer_empty_n,
        imgBayer_read,
        imgG_din,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgG_full_n,
        imgG_write,
        height,
        width,
        bayerPhase_read,
        bayerPhase_c9_din,
        bayerPhase_c9_num_data_valid,
        bayerPhase_c9_fifo_cap,
        bayerPhase_c9_full_n,
        bayerPhase_c9_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] imgBayer_dout;
input  [2:0] imgBayer_num_data_valid;
input  [2:0] imgBayer_fifo_cap;
input   imgBayer_empty_n;
output   imgBayer_read;
output  [47:0] imgG_din;
input  [2:0] imgG_num_data_valid;
input  [2:0] imgG_fifo_cap;
input   imgG_full_n;
output   imgG_write;
input  [15:0] height;
input  [15:0] width;
input  [15:0] bayerPhase_read;
output  [15:0] bayerPhase_c9_din;
input  [2:0] bayerPhase_c9_num_data_valid;
input  [2:0] bayerPhase_c9_fifo_cap;
input   bayerPhase_c9_full_n;
output   bayerPhase_c9_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgBayer_read;
reg imgG_write;
reg bayerPhase_c9_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
reg    ap_block_state1;
wire   [16:0] zext_ln274_fu_272_p1;
reg   [16:0] zext_ln274_reg_597;
wire   [16:0] loopHeight_fu_276_p2;
reg   [16:0] loopHeight_reg_602;
reg   [14:0] trunc_ln293_1_reg_607;
wire   [14:0] zext_ln294_fu_300_p1;
reg   [14:0] zext_ln294_reg_613;
wire   [15:0] add_ln315_1_fu_320_p2;
reg   [15:0] add_ln315_1_reg_618;
wire   [14:0] xor229_1_cast_fu_332_p1;
reg   [14:0] xor229_1_cast_reg_623;
reg   [7:0] p_lcssa5106_load_reg_631;
wire    ap_CS_fsm_state2;
reg   [7:0] p_lcssa50835108_load_reg_636;
reg   [7:0] p_lcssa50855110_load_reg_641;
reg   [7:0] p_lcssa50875112_load_reg_646;
reg   [7:0] p_lcssa50895114_load_reg_651;
reg   [7:0] p_lcssa50915116_load_reg_656;
reg   [7:0] p_lcssa50935118_load_reg_661;
reg   [7:0] p_lcssa50955120_load_reg_666;
reg   [7:0] p_lcssa50975122_load_reg_671;
reg   [7:0] p_lcssa50995124_load_reg_676;
reg   [7:0] p_lcssa51845215_load_reg_681;
reg   [7:0] p_lcssa51855217_load_reg_686;
reg   [7:0] p_lcssa51865219_load_reg_691;
reg   [7:0] p_lcssa51875221_load_reg_696;
reg   [7:0] p_lcssa51885223_load_reg_701;
reg   [7:0] p_lcssa51895225_load_reg_706;
reg   [7:0] p_lcssa51905227_load_reg_711;
reg   [7:0] p_lcssa51915229_load_reg_716;
reg   [7:0] p_lcssa51925231_load_reg_721;
reg   [7:0] p_lcssa51935233_load_reg_726;
wire   [16:0] out_y_fu_415_p2;
reg   [16:0] out_y_reg_731;
wire   [0:0] cmp689_fu_434_p2;
reg   [0:0] cmp689_reg_736;
wire   [0:0] cmp84_fu_439_p2;
reg   [0:0] cmp84_reg_741;
wire   [0:0] cmp170_fu_444_p2;
reg   [0:0] cmp170_reg_746;
wire   [0:0] cmp230_fu_450_p2;
reg   [0:0] cmp230_reg_751;
wire   [0:0] cmp230_1_fu_455_p2;
reg   [0:0] cmp230_1_reg_756;
wire   [15:0] linebuf_yuv_q1;
wire   [15:0] linebuf_yuv_1_q1;
wire   [15:0] linebuf_yuv_2_q1;
wire   [15:0] linebuf_yuv_3_q1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_done;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_idle;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_ready;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgBayer_read;
wire   [47:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_din;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_write;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_we0;
wire   [15:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_we0;
wire   [15:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_we0;
wire   [15:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_we0;
wire   [15:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce1;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18_ap_vld;
wire   [7:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19_ap_vld;
reg    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] p_lcssa51935233_fu_162;
reg   [7:0] p_lcssa51925231_fu_158;
reg   [7:0] p_lcssa51915229_fu_154;
reg   [7:0] p_lcssa51905227_fu_150;
reg   [7:0] p_lcssa51895225_fu_146;
reg   [7:0] p_lcssa51885223_fu_142;
reg   [7:0] p_lcssa51875221_fu_138;
reg   [7:0] p_lcssa51865219_fu_134;
reg   [7:0] p_lcssa51855217_fu_130;
reg   [7:0] p_lcssa51845215_fu_126;
reg   [7:0] p_lcssa50995124_fu_122;
reg   [7:0] p_lcssa50975122_fu_118;
reg   [7:0] p_lcssa50955120_fu_114;
reg   [7:0] p_lcssa50935118_fu_110;
reg   [7:0] p_lcssa50915116_fu_106;
reg   [7:0] p_lcssa50895114_fu_102;
reg   [7:0] p_lcssa50875112_fu_98;
reg   [7:0] p_lcssa50855110_fu_94;
reg   [7:0] p_lcssa50835108_fu_90;
reg   [7:0] p_lcssa5106_fu_86;
reg   [16:0] y_fu_82;
wire   [16:0] y_8_fu_349_p2;
wire   [0:0] icmp_ln315_fu_344_p2;
wire   [0:0] x_phase_fu_286_p1;
wire   [16:0] zext_ln283_fu_282_p1;
wire   [16:0] add_ln315_fu_304_p2;
wire   [15:0] trunc_ln_fu_310_p4;
wire   [0:0] xor229_1_fu_326_p2;
wire   [0:0] empty_fu_421_p1;
wire   [14:0] and226_cast_fu_425_p1;
wire   [14:0] xor_fu_429_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg = 1'b0;
#0 y_fu_82 = 17'd0;
end

system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce1),
    .q1(linebuf_yuv_q1)
);

system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce1),
    .q1(linebuf_yuv_1_q1)
);

system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce1),
    .q1(linebuf_yuv_2_q1)
);

system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce1),
    .q1(linebuf_yuv_3_q1)
);

system_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4 grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start),
    .ap_done(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_done),
    .ap_idle(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_idle),
    .ap_ready(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_ready),
    .imgBayer_dout(imgBayer_dout),
    .imgBayer_num_data_valid(3'd0),
    .imgBayer_fifo_cap(3'd0),
    .imgBayer_empty_n(imgBayer_empty_n),
    .imgBayer_read(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgBayer_read),
    .imgG_din(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_din),
    .imgG_num_data_valid(3'd0),
    .imgG_fifo_cap(3'd0),
    .imgG_full_n(imgG_full_n),
    .imgG_write(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_write),
    .p_lcssa51935233(p_lcssa51935233_load_reg_726),
    .p_lcssa51925231(p_lcssa51925231_load_reg_721),
    .p_lcssa51915229(p_lcssa51915229_load_reg_716),
    .p_lcssa51905227(p_lcssa51905227_load_reg_711),
    .p_lcssa51895225(p_lcssa51895225_load_reg_706),
    .p_lcssa51885223(p_lcssa51885223_load_reg_701),
    .p_lcssa51875221(p_lcssa51875221_load_reg_696),
    .p_lcssa51865219(p_lcssa51865219_load_reg_691),
    .p_lcssa51855217(p_lcssa51855217_load_reg_686),
    .p_lcssa51845215(p_lcssa51845215_load_reg_681),
    .p_lcssa50995124(p_lcssa50995124_load_reg_676),
    .p_lcssa50975122(p_lcssa50975122_load_reg_671),
    .p_lcssa50955120(p_lcssa50955120_load_reg_666),
    .p_lcssa50935118(p_lcssa50935118_load_reg_661),
    .p_lcssa50915116(p_lcssa50915116_load_reg_656),
    .p_lcssa50895114(p_lcssa50895114_load_reg_651),
    .p_lcssa50875112(p_lcssa50875112_load_reg_646),
    .p_lcssa50855110(p_lcssa50855110_load_reg_641),
    .p_lcssa50835108(p_lcssa50835108_load_reg_636),
    .p_lcssa5106(p_lcssa5106_load_reg_631),
    .add_ln315_1(add_ln315_1_reg_618),
    .out_y(out_y_reg_731),
    .cmp689(cmp689_reg_736),
    .cmp230_1(cmp230_1_reg_756),
    .cmp230(cmp230_reg_751),
    .linebuf_yuv_3_address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address0),
    .linebuf_yuv_3_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce0),
    .linebuf_yuv_3_we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_we0),
    .linebuf_yuv_3_d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_d0),
    .linebuf_yuv_3_address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_address1),
    .linebuf_yuv_3_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_3_ce1),
    .linebuf_yuv_3_q1(linebuf_yuv_3_q1),
    .linebuf_yuv_2_address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address0),
    .linebuf_yuv_2_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce0),
    .linebuf_yuv_2_we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_we0),
    .linebuf_yuv_2_d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_d0),
    .linebuf_yuv_2_address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_address1),
    .linebuf_yuv_2_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_2_ce1),
    .linebuf_yuv_2_q1(linebuf_yuv_2_q1),
    .linebuf_yuv_1_address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address0),
    .linebuf_yuv_1_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce0),
    .linebuf_yuv_1_we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_we0),
    .linebuf_yuv_1_d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_d0),
    .linebuf_yuv_1_address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_address1),
    .linebuf_yuv_1_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_1_ce1),
    .linebuf_yuv_1_q1(linebuf_yuv_1_q1),
    .linebuf_yuv_address0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address0),
    .linebuf_yuv_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce0),
    .linebuf_yuv_we0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_we0),
    .linebuf_yuv_d0(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_d0),
    .linebuf_yuv_address1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_address1),
    .linebuf_yuv_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_linebuf_yuv_ce1),
    .linebuf_yuv_q1(linebuf_yuv_q1),
    .zext_ln283(width),
    .cmp170(cmp170_reg_746),
    .cmp84(cmp84_reg_741),
    .p_out(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out),
    .p_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out_ap_vld),
    .p_out1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1),
    .p_out1_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1_ap_vld),
    .p_out2(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2),
    .p_out2_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2_ap_vld),
    .p_out3(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3),
    .p_out3_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3_ap_vld),
    .p_out4(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4),
    .p_out4_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4_ap_vld),
    .p_out5(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5),
    .p_out5_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5_ap_vld),
    .p_out6(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6),
    .p_out6_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6_ap_vld),
    .p_out7(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7),
    .p_out7_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7_ap_vld),
    .p_out8(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8),
    .p_out8_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8_ap_vld),
    .p_out9(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9),
    .p_out9_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9_ap_vld),
    .p_out10(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10),
    .p_out10_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10_ap_vld),
    .p_out11(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11),
    .p_out11_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11_ap_vld),
    .p_out12(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12),
    .p_out12_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12_ap_vld),
    .p_out13(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13),
    .p_out13_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13_ap_vld),
    .p_out14(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14),
    .p_out14_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14_ap_vld),
    .p_out15(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15),
    .p_out15_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15_ap_vld),
    .p_out16(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16),
    .p_out16_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16_ap_vld),
    .p_out17(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17),
    .p_out17_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17_ap_vld),
    .p_out18(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18),
    .p_out18_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18_ap_vld),
    .p_out19(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19),
    .p_out19_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln315_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_NS_fsm_state3))) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_ready == 1'b1)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_82 <= 17'd0;
    end else if (((icmp_ln315_fu_344_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_82 <= y_8_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln315_1_reg_618 <= add_ln315_1_fu_320_p2;
        loopHeight_reg_602 <= loopHeight_fu_276_p2;
        trunc_ln293_1_reg_607 <= {{bayerPhase_read[15:1]}};
        xor229_1_cast_reg_623[0] <= xor229_1_cast_fu_332_p1[0];
        zext_ln274_reg_597[15 : 0] <= zext_ln274_fu_272_p1[15 : 0];
        zext_ln294_reg_613[0] <= zext_ln294_fu_300_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp170_reg_746 <= cmp170_fu_444_p2;
        cmp230_1_reg_756 <= cmp230_1_fu_455_p2;
        cmp230_reg_751 <= cmp230_fu_450_p2;
        cmp689_reg_736 <= cmp689_fu_434_p2;
        cmp84_reg_741 <= cmp84_fu_439_p2;
        out_y_reg_731 <= out_y_fu_415_p2;
        p_lcssa50835108_load_reg_636 <= p_lcssa50835108_fu_90;
        p_lcssa50855110_load_reg_641 <= p_lcssa50855110_fu_94;
        p_lcssa50875112_load_reg_646 <= p_lcssa50875112_fu_98;
        p_lcssa50895114_load_reg_651 <= p_lcssa50895114_fu_102;
        p_lcssa50915116_load_reg_656 <= p_lcssa50915116_fu_106;
        p_lcssa50935118_load_reg_661 <= p_lcssa50935118_fu_110;
        p_lcssa50955120_load_reg_666 <= p_lcssa50955120_fu_114;
        p_lcssa50975122_load_reg_671 <= p_lcssa50975122_fu_118;
        p_lcssa50995124_load_reg_676 <= p_lcssa50995124_fu_122;
        p_lcssa5106_load_reg_631 <= p_lcssa5106_fu_86;
        p_lcssa51845215_load_reg_681 <= p_lcssa51845215_fu_126;
        p_lcssa51855217_load_reg_686 <= p_lcssa51855217_fu_130;
        p_lcssa51865219_load_reg_691 <= p_lcssa51865219_fu_134;
        p_lcssa51875221_load_reg_696 <= p_lcssa51875221_fu_138;
        p_lcssa51885223_load_reg_701 <= p_lcssa51885223_fu_142;
        p_lcssa51895225_load_reg_706 <= p_lcssa51895225_fu_146;
        p_lcssa51905227_load_reg_711 <= p_lcssa51905227_fu_150;
        p_lcssa51915229_load_reg_716 <= p_lcssa51915229_fu_154;
        p_lcssa51925231_load_reg_721 <= p_lcssa51925231_fu_158;
        p_lcssa51935233_load_reg_726 <= p_lcssa51935233_fu_162;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50835108_fu_90 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50855110_fu_94 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50875112_fu_98 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50895114_fu_102 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50915116_fu_106 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50935118_fu_110 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50955120_fu_114 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50975122_fu_118 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50995124_fu_122 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa5106_fu_86 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out19;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51845215_fu_126 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out9;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51855217_fu_130 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51865219_fu_134 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51875221_fu_138 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51885223_fu_142 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51895225_fu_146 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51905227_fu_150 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51915229_fu_154 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51925231_fu_158 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa51935233_fu_162 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_p_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_full_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_write = 1'b1;
    end else begin
        bayerPhase_c9_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgBayer_read = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgBayer_read;
    end else begin
        imgBayer_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgG_write = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_write;
    end else begin
        imgG_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln315_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln315_1_fu_320_p2 = (trunc_ln_fu_310_p4 + 16'd1);

assign add_ln315_fu_304_p2 = (zext_ln283_fu_282_p1 + 17'd1);

assign and226_cast_fu_425_p1 = empty_fu_421_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c9_din = bayerPhase_read;

assign cmp170_fu_444_p2 = ((y_fu_82 != 17'd0) ? 1'b1 : 1'b0);

assign cmp230_1_fu_455_p2 = ((xor_fu_429_p2 == xor229_1_cast_reg_623) ? 1'b1 : 1'b0);

assign cmp230_fu_450_p2 = ((xor_fu_429_p2 == zext_ln294_reg_613) ? 1'b1 : 1'b0);

assign cmp689_fu_434_p2 = ((and226_cast_fu_425_p1 == trunc_ln293_1_reg_607) ? 1'b1 : 1'b0);

assign cmp84_fu_439_p2 = ((y_fu_82 < zext_ln274_reg_597) ? 1'b1 : 1'b0);

assign empty_fu_421_p1 = out_y_fu_415_p2[0:0];

assign grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_ap_start_reg;

assign icmp_ln315_fu_344_p2 = ((y_fu_82 == loopHeight_reg_602) ? 1'b1 : 1'b0);

assign imgG_din = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_208_imgG_din;

assign loopHeight_fu_276_p2 = (zext_ln274_fu_272_p1 + 17'd2);

assign out_y_fu_415_p2 = ($signed(y_fu_82) + $signed(17'd131070));

assign start_out = real_start;

assign trunc_ln_fu_310_p4 = {{add_ln315_fu_304_p2[16:1]}};

assign x_phase_fu_286_p1 = bayerPhase_read[0:0];

assign xor229_1_cast_fu_332_p1 = xor229_1_fu_326_p2;

assign xor229_1_fu_326_p2 = (x_phase_fu_286_p1 ^ 1'd1);

assign xor_fu_429_p2 = (trunc_ln293_1_reg_607 ^ and226_cast_fu_425_p1);

assign y_8_fu_349_p2 = (y_fu_82 + 17'd1);

assign zext_ln274_fu_272_p1 = height;

assign zext_ln283_fu_282_p1 = width;

assign zext_ln294_fu_300_p1 = x_phase_fu_286_p1;

always @ (posedge ap_clk) begin
    zext_ln274_reg_597[16] <= 1'b0;
    zext_ln294_reg_613[14:1] <= 14'b00000000000000;
    xor229_1_cast_reg_623[14:1] <= 14'b00000000000000;
end

endmodule //system_v_demosaic_0_0_DebayerG
