// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_2d50_csc_0_v_vcresampler_core_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_dout,
        stream_in_num_data_valid,
        stream_in_fifo_cap,
        stream_in_empty_n,
        stream_in_read,
        HwReg_height_dout,
        HwReg_height_num_data_valid,
        HwReg_height_fifo_cap,
        HwReg_height_empty_n,
        HwReg_height_read,
        HwReg_width_dout,
        HwReg_width_num_data_valid,
        HwReg_width_fifo_cap,
        HwReg_width_empty_n,
        HwReg_width_read,
        p_read,
        stream_in_vresampled_din,
        stream_in_vresampled_num_data_valid,
        stream_in_vresampled_fifo_cap,
        stream_in_vresampled_full_n,
        stream_in_vresampled_write,
        HwReg_width_c22_din,
        HwReg_width_c22_num_data_valid,
        HwReg_width_c22_fifo_cap,
        HwReg_width_c22_full_n,
        HwReg_width_c22_write,
        HwReg_height_c28_din,
        HwReg_height_c28_num_data_valid,
        HwReg_height_c28_fifo_cap,
        HwReg_height_c28_full_n,
        HwReg_height_c28_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] stream_in_dout;
input  [4:0] stream_in_num_data_valid;
input  [4:0] stream_in_fifo_cap;
input   stream_in_empty_n;
output   stream_in_read;
input  [11:0] HwReg_height_dout;
input  [2:0] HwReg_height_num_data_valid;
input  [2:0] HwReg_height_fifo_cap;
input   HwReg_height_empty_n;
output   HwReg_height_read;
input  [11:0] HwReg_width_dout;
input  [2:0] HwReg_width_num_data_valid;
input  [2:0] HwReg_width_fifo_cap;
input   HwReg_width_empty_n;
output   HwReg_width_read;
input  [0:0] p_read;
output  [47:0] stream_in_vresampled_din;
input  [4:0] stream_in_vresampled_num_data_valid;
input  [4:0] stream_in_vresampled_fifo_cap;
input   stream_in_vresampled_full_n;
output   stream_in_vresampled_write;
output  [11:0] HwReg_width_c22_din;
input  [2:0] HwReg_width_c22_num_data_valid;
input  [2:0] HwReg_width_c22_fifo_cap;
input   HwReg_width_c22_full_n;
output   HwReg_width_c22_write;
output  [11:0] HwReg_height_c28_din;
input  [2:0] HwReg_height_c28_num_data_valid;
input  [2:0] HwReg_height_c28_fifo_cap;
input   HwReg_height_c28_full_n;
output   HwReg_height_c28_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_in_read;
reg HwReg_height_read;
reg HwReg_width_read;
reg stream_in_vresampled_write;
reg HwReg_width_c22_write;
reg HwReg_height_c28_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    HwReg_height_blk_n;
reg    HwReg_width_blk_n;
reg    HwReg_width_c22_blk_n;
reg    HwReg_height_c28_blk_n;
reg    ap_block_state1;
wire   [13:0] select_ln996_fu_199_p3;
reg   [13:0] select_ln996_reg_362;
wire   [12:0] zext_ln996_fu_207_p1;
reg   [12:0] zext_ln996_reg_367;
reg   [10:0] trunc_ln_reg_372;
wire   [12:0] add_ln998_fu_229_p2;
reg   [12:0] add_ln998_reg_377;
wire   [0:0] empty_fu_258_p1;
reg   [0:0] empty_reg_385;
wire    ap_CS_fsm_state2;
wire   [0:0] empty_70_fu_268_p1;
reg   [0:0] empty_70_reg_390;
wire   [0:0] cmp33_i_fu_273_p2;
reg   [0:0] cmp33_i_reg_395;
wire   [0:0] cmp105_i_fu_279_p2;
reg   [0:0] cmp105_i_reg_400;
reg   [0:0] tmp_reg_405;
wire   [15:0] linebuf_y_q1;
wire   [15:0] linebuf_y_1_q1;
wire   [15:0] linebuf_c_q1;
wire   [15:0] linebuf_c_1_q1;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_done;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_idle;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_ready;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_read;
wire   [47:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_din;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_write;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_we0;
wire   [15:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_d0;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address1;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce1;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_we0;
wire   [15:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_d0;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address1;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce1;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_we0;
wire   [15:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_d0;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address1;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce1;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce0;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_we0;
wire   [15:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_d0;
wire   [10:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address1;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce1;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o;
wire    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o_ap_vld;
reg    grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg;
wire   [0:0] icmp_ln998_fu_243_p2;
wire    ap_CS_fsm_state3;
reg   [7:0] p_lcssa619669_i_fu_112;
reg   [7:0] p_lcssa618666_i_fu_108;
reg   [7:0] p_lcssa617663_i_fu_104;
reg   [7:0] p_lcssa616660_i_fu_100;
reg   [7:0] pix_0_5_0_0_0_load615_lcssa657_i_fu_96;
reg   [7:0] pix_0_4_0_0_0_load613_lcssa654_i_fu_92;
reg   [7:0] pix_0_3_0_0_0_load611_lcssa651_i_fu_88;
reg   [7:0] pix_0_2_0_0_0_load609_lcssa648_i_fu_84;
reg   [7:0] pix_0_1_0_0_0_load607_lcssa645_i_fu_80;
reg   [7:0] pix_0_0_0_0_0_load605_lcssa642_i_fu_76;
reg   [12:0] y_fu_116;
wire   [12:0] add_ln998_1_fu_248_p2;
wire   [12:0] select_ln998_fu_221_p3;
wire   [13:0] y_cast15_i_fu_254_p1;
wire   [13:0] out_y_fu_263_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg = 1'b0;
#0 y_fu_116 = 13'd0;
end

bd_2d50_csc_0_v_vcresampler_core_1_linebuf_y_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address0),
    .ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce0),
    .we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_we0),
    .d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_d0),
    .address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address1),
    .ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce1),
    .q1(linebuf_y_q1)
);

bd_2d50_csc_0_v_vcresampler_core_1_linebuf_y_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_y_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address0),
    .ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce0),
    .we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_we0),
    .d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_d0),
    .address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address1),
    .ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce1),
    .q1(linebuf_y_1_q1)
);

bd_2d50_csc_0_v_vcresampler_core_1_linebuf_y_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address0),
    .ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce0),
    .we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_we0),
    .d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_d0),
    .address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address1),
    .ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce1),
    .q1(linebuf_c_q1)
);

bd_2d50_csc_0_v_vcresampler_core_1_linebuf_y_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
linebuf_c_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address0),
    .ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce0),
    .we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_we0),
    .d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_d0),
    .address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address1),
    .ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce1),
    .q1(linebuf_c_1_q1)
);

bd_2d50_csc_0_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2 grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start),
    .ap_done(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_done),
    .ap_idle(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_idle),
    .ap_ready(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_ready),
    .stream_in_dout(stream_in_dout),
    .stream_in_num_data_valid(5'd0),
    .stream_in_fifo_cap(5'd0),
    .stream_in_empty_n(stream_in_empty_n),
    .stream_in_read(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_read),
    .stream_in_vresampled_din(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_din),
    .stream_in_vresampled_num_data_valid(5'd0),
    .stream_in_vresampled_fifo_cap(5'd0),
    .stream_in_vresampled_full_n(stream_in_vresampled_full_n),
    .stream_in_vresampled_write(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_write),
    .trunc_ln(trunc_ln_reg_372),
    .p_read(p_read),
    .empty_40(empty_70_reg_390),
    .empty_41(tmp_reg_405),
    .linebuf_y_address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address0),
    .linebuf_y_ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce0),
    .linebuf_y_we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_we0),
    .linebuf_y_d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_d0),
    .linebuf_y_address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_address1),
    .linebuf_y_ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_ce1),
    .linebuf_y_q1(linebuf_y_q1),
    .linebuf_y_1_address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address0),
    .linebuf_y_1_ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce0),
    .linebuf_y_1_we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_we0),
    .linebuf_y_1_d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_d0),
    .linebuf_y_1_address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_address1),
    .linebuf_y_1_ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_y_1_ce1),
    .linebuf_y_1_q1(linebuf_y_1_q1),
    .cmp105_i(cmp105_i_reg_400),
    .linebuf_c_address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address0),
    .linebuf_c_ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce0),
    .linebuf_c_we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_we0),
    .linebuf_c_d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_d0),
    .linebuf_c_address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_address1),
    .linebuf_c_ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_ce1),
    .linebuf_c_q1(linebuf_c_q1),
    .linebuf_c_1_address0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address0),
    .linebuf_c_1_ce0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce0),
    .linebuf_c_1_we0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_we0),
    .linebuf_c_1_d0(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_d0),
    .linebuf_c_1_address1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_address1),
    .linebuf_c_1_ce1(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_linebuf_c_1_ce1),
    .linebuf_c_1_q1(linebuf_c_1_q1),
    .empty(empty_reg_385),
    .cmp33_i(cmp33_i_reg_395),
    .p_out_i(p_lcssa619669_i_fu_112),
    .p_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o),
    .p_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o_ap_vld),
    .p_out1_i(p_lcssa618666_i_fu_108),
    .p_out1_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o),
    .p_out1_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o_ap_vld),
    .p_out2_i(p_lcssa617663_i_fu_104),
    .p_out2_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o),
    .p_out2_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o_ap_vld),
    .p_out3_i(p_lcssa616660_i_fu_100),
    .p_out3_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o),
    .p_out3_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o_ap_vld),
    .pix_0_5_0_0_0_load614_i_out_i(pix_0_5_0_0_0_load615_lcssa657_i_fu_96),
    .pix_0_5_0_0_0_load614_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o),
    .pix_0_5_0_0_0_load614_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o_ap_vld),
    .pix_0_4_0_0_0_load612_i_out_i(pix_0_4_0_0_0_load613_lcssa654_i_fu_92),
    .pix_0_4_0_0_0_load612_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o),
    .pix_0_4_0_0_0_load612_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o_ap_vld),
    .pix_0_3_0_0_0_load610_i_out_i(pix_0_3_0_0_0_load611_lcssa651_i_fu_88),
    .pix_0_3_0_0_0_load610_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o),
    .pix_0_3_0_0_0_load610_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o_ap_vld),
    .pix_0_2_0_0_0_load608_i_out_i(pix_0_2_0_0_0_load609_lcssa648_i_fu_84),
    .pix_0_2_0_0_0_load608_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o),
    .pix_0_2_0_0_0_load608_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o_ap_vld),
    .pix_0_1_0_0_0_load606_i_out_i(pix_0_1_0_0_0_load607_lcssa645_i_fu_80),
    .pix_0_1_0_0_0_load606_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o),
    .pix_0_1_0_0_0_load606_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o_ap_vld),
    .pix_0_0_0_0_0_load604_i_out_i(pix_0_0_0_0_0_load605_lcssa642_i_fu_76),
    .pix_0_0_0_0_0_load604_i_out_o(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o),
    .pix_0_0_0_0_0_load604_i_out_o_ap_vld(grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln998_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln998_fu_243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_ready == 1'b1)) begin
            grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_116 <= 13'd0;
    end else if (((icmp_ln998_fu_243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_116 <= add_ln998_1_fu_248_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln998_reg_377 <= add_ln998_fu_229_p2;
        select_ln996_reg_362[1] <= select_ln996_fu_199_p3[1];
        trunc_ln_reg_372 <= {{HwReg_width_dout[11:1]}};
        zext_ln996_reg_367[11 : 0] <= zext_ln996_fu_207_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp105_i_reg_400 <= cmp105_i_fu_279_p2;
        cmp33_i_reg_395 <= cmp33_i_fu_273_p2;
        empty_70_reg_390 <= empty_70_fu_268_p1;
        empty_reg_385 <= empty_fu_258_p1;
        tmp_reg_405 <= out_y_fu_263_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_lcssa616660_i_fu_100 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_lcssa617663_i_fu_104 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_lcssa618666_i_fu_108 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_lcssa619669_i_fu_112 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_p_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_0_0_0_0_load605_lcssa642_i_fu_76 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_0_0_0_0_load604_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_1_0_0_0_load607_lcssa645_i_fu_80 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_1_0_0_0_load606_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_2_0_0_0_load609_lcssa648_i_fu_84 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_2_0_0_0_load608_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_3_0_0_0_load611_lcssa651_i_fu_88 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_3_0_0_0_load610_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_4_0_0_0_load613_lcssa654_i_fu_92 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_4_0_0_0_load612_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        pix_0_5_0_0_0_load615_lcssa657_i_fu_96 <= grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_pix_0_5_0_0_0_load614_i_out_o;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_blk_n = HwReg_height_empty_n;
    end else begin
        HwReg_height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c28_blk_n = HwReg_height_c28_full_n;
    end else begin
        HwReg_height_c28_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c28_write = 1'b1;
    end else begin
        HwReg_height_c28_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_read = 1'b1;
    end else begin
        HwReg_height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_blk_n = HwReg_width_empty_n;
    end else begin
        HwReg_width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c22_blk_n = HwReg_width_c22_full_n;
    end else begin
        HwReg_width_c22_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c22_write = 1'b1;
    end else begin
        HwReg_width_c22_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_read = 1'b1;
    end else begin
        HwReg_width_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln998_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln998_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_read = grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_read;
    end else begin
        stream_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_vresampled_write = grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_write;
    end else begin
        stream_in_vresampled_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln998_fu_243_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_height_c28_din = HwReg_height_dout;

assign HwReg_width_c22_din = HwReg_width_dout;

assign add_ln998_1_fu_248_p2 = (y_fu_116 + 13'd1);

assign add_ln998_fu_229_p2 = (select_ln998_fu_221_p3 + zext_ln996_fu_207_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == HwReg_height_c28_full_n) | (1'b0 == HwReg_width_c22_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1));
end

assign cmp105_i_fu_279_p2 = ((y_fu_116 != 13'd0) ? 1'b1 : 1'b0);

assign cmp33_i_fu_273_p2 = ((y_fu_116 < zext_ln996_reg_367) ? 1'b1 : 1'b0);

assign empty_70_fu_268_p1 = out_y_fu_263_p2[0:0];

assign empty_fu_258_p1 = y_fu_116[0:0];

assign grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start = grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_ap_start_reg;

assign icmp_ln998_fu_243_p2 = ((y_fu_116 == add_ln998_reg_377) ? 1'b1 : 1'b0);

assign out_y_fu_263_p2 = (y_cast15_i_fu_254_p1 - select_ln996_reg_362);

assign select_ln996_fu_199_p3 = ((p_read[0:0] == 1'b1) ? 14'd0 : 14'd2);

assign select_ln998_fu_221_p3 = ((p_read[0:0] == 1'b1) ? 13'd0 : 13'd2);

assign stream_in_vresampled_din = grp_v_vcresampler_core_1_Pipeline_VITIS_LOOP_1000_2_fu_170_stream_in_vresampled_din;

assign y_cast15_i_fu_254_p1 = y_fu_116;

assign zext_ln996_fu_207_p1 = HwReg_height_dout;

always @ (posedge ap_clk) begin
    select_ln996_reg_362[0] <= 1'b0;
    select_ln996_reg_362[13:2] <= 12'b000000000000;
    zext_ln996_reg_367[12] <= 1'b0;
end

endmodule //bd_2d50_csc_0_v_vcresampler_core_1
