// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_2d50_csc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_664_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_out_vresampled_dout,
        stream_out_vresampled_num_data_valid,
        stream_out_vresampled_fifo_cap,
        stream_out_vresampled_empty_n,
        stream_out_vresampled_read,
        m_axis_video_TREADY,
        sof,
        div207_cast,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        p_read,
        sub
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] stream_out_vresampled_dout;
input  [4:0] stream_out_vresampled_num_data_valid;
input  [4:0] stream_out_vresampled_fifo_cap;
input   stream_out_vresampled_empty_n;
output   stream_out_vresampled_read;
input   m_axis_video_TREADY;
input  [0:0] sof;
input  [10:0] div207_cast;
output  [47:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [7:0] p_read;
input  [10:0] sub;

reg ap_idle;
reg stream_out_vresampled_read;
reg m_axis_video_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln664_reg_581;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln664_fu_262_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_out_vresampled_blk_n;
reg   [0:0] sof_2_reg_175;
wire   [7:0] p_read_9_reg_572;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] axi_last_fu_274_p2;
reg   [0:0] axi_last_reg_585;
wire    ap_loop_init;
reg   [8:0] ap_phi_mux_axi_data_2_phi_fu_190_p6;
wire   [8:0] axi_data_fu_357_p3;
wire   [8:0] ap_phi_reg_pp0_iter1_axi_data_2_reg_187;
wire   [8:0] axi_data_3_fu_339_p3;
wire   [8:0] axi_data_1_fu_348_p3;
reg   [47:0] ap_phi_mux_axi_data_7_phi_fu_201_p6;
wire   [47:0] axi_data_4_fu_396_p5;
wire   [47:0] ap_phi_reg_pp0_iter1_axi_data_7_reg_198;
wire   [47:0] axi_data_6_fu_370_p5;
wire   [47:0] axi_data_5_fu_383_p5;
reg   [47:0] ap_phi_mux_axi_data_11_phi_fu_212_p6;
wire   [47:0] axi_data_8_fu_435_p5;
wire   [47:0] ap_phi_reg_pp0_iter1_axi_data_11_reg_209;
wire   [47:0] axi_data_10_fu_409_p5;
wire   [47:0] axi_data_9_fu_422_p5;
reg   [47:0] ap_phi_mux_axi_data_15_phi_fu_223_p6;
wire   [47:0] axi_data_12_fu_474_p5;
wire   [47:0] ap_phi_reg_pp0_iter1_axi_data_15_reg_220;
wire   [47:0] axi_data_14_fu_448_p5;
wire   [47:0] axi_data_13_fu_461_p5;
reg   [47:0] ap_phi_mux_axi_data_19_phi_fu_234_p6;
wire   [47:0] axi_data_16_fu_513_p5;
wire   [47:0] ap_phi_reg_pp0_iter1_axi_data_19_reg_231;
wire   [47:0] axi_data_18_fu_487_p5;
wire   [47:0] axi_data_17_fu_500_p5;
reg   [47:0] ap_phi_mux_axi_data_23_phi_fu_245_p6;
wire   [47:0] axi_data_20_fu_552_p5;
wire   [47:0] ap_phi_reg_pp0_iter1_axi_data_23_reg_242;
wire   [47:0] axi_data_22_fu_526_p5;
wire   [47:0] axi_data_21_fu_539_p5;
reg   [10:0] j_fu_112;
wire   [10:0] j_2_fu_268_p2;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] pix_rgb_3_fu_285_p1;
wire   [7:0] pix_444_fu_289_p4;
wire  signed [47:0] sext_ln618_fu_366_p1;
wire   [7:0] pix_422_fu_299_p4;
wire   [7:0] pix_rgb_fu_309_p4;
wire   [7:0] pix_444_2_fu_319_p4;
wire   [7:0] pix_444_3_fu_329_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_365;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_112 = 11'd0;
#0 ap_done_reg = 1'b0;
end

bd_2d50_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln664_fu_262_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_112 <= j_2_fu_268_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_112 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_365)) begin
            sof_2_reg_175 <= 1'd0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            sof_2_reg_175 <= sof;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_last_reg_585 <= axi_last_fu_274_p2;
        icmp_ln664_reg_581 <= icmp_ln664_fu_262_p2;
    end
end

always @ (*) begin
    if (((icmp_ln664_fu_262_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_11_phi_fu_212_p6 = axi_data_9_fu_422_p5;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_11_phi_fu_212_p6 = axi_data_10_fu_409_p5;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_11_phi_fu_212_p6 = axi_data_8_fu_435_p5;
        end else begin
            ap_phi_mux_axi_data_11_phi_fu_212_p6 = ap_phi_reg_pp0_iter1_axi_data_11_reg_209;
        end
    end else begin
        ap_phi_mux_axi_data_11_phi_fu_212_p6 = ap_phi_reg_pp0_iter1_axi_data_11_reg_209;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_15_phi_fu_223_p6 = axi_data_13_fu_461_p5;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_15_phi_fu_223_p6 = axi_data_14_fu_448_p5;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_15_phi_fu_223_p6 = axi_data_12_fu_474_p5;
        end else begin
            ap_phi_mux_axi_data_15_phi_fu_223_p6 = ap_phi_reg_pp0_iter1_axi_data_15_reg_220;
        end
    end else begin
        ap_phi_mux_axi_data_15_phi_fu_223_p6 = ap_phi_reg_pp0_iter1_axi_data_15_reg_220;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_19_phi_fu_234_p6 = axi_data_17_fu_500_p5;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_19_phi_fu_234_p6 = axi_data_18_fu_487_p5;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_19_phi_fu_234_p6 = axi_data_16_fu_513_p5;
        end else begin
            ap_phi_mux_axi_data_19_phi_fu_234_p6 = ap_phi_reg_pp0_iter1_axi_data_19_reg_231;
        end
    end else begin
        ap_phi_mux_axi_data_19_phi_fu_234_p6 = ap_phi_reg_pp0_iter1_axi_data_19_reg_231;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_23_phi_fu_245_p6 = axi_data_21_fu_539_p5;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_23_phi_fu_245_p6 = axi_data_22_fu_526_p5;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_23_phi_fu_245_p6 = axi_data_20_fu_552_p5;
        end else begin
            ap_phi_mux_axi_data_23_phi_fu_245_p6 = ap_phi_reg_pp0_iter1_axi_data_23_reg_242;
        end
    end else begin
        ap_phi_mux_axi_data_23_phi_fu_245_p6 = ap_phi_reg_pp0_iter1_axi_data_23_reg_242;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_2_phi_fu_190_p6 = axi_data_1_fu_348_p3;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_2_phi_fu_190_p6 = axi_data_3_fu_339_p3;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_2_phi_fu_190_p6 = axi_data_fu_357_p3;
        end else begin
            ap_phi_mux_axi_data_2_phi_fu_190_p6 = ap_phi_reg_pp0_iter1_axi_data_2_reg_187;
        end
    end else begin
        ap_phi_mux_axi_data_2_phi_fu_190_p6 = ap_phi_reg_pp0_iter1_axi_data_2_reg_187;
    end
end

always @ (*) begin
    if ((icmp_ln664_reg_581 == 1'd0)) begin
        if ((p_read_9_reg_572 == 8'd0)) begin
            ap_phi_mux_axi_data_7_phi_fu_201_p6 = axi_data_5_fu_383_p5;
        end else if ((p_read_9_reg_572 == 8'd1)) begin
            ap_phi_mux_axi_data_7_phi_fu_201_p6 = axi_data_6_fu_370_p5;
        end else if ((~(p_read_9_reg_572 == 8'd1) & ~(p_read_9_reg_572 == 8'd0))) begin
            ap_phi_mux_axi_data_7_phi_fu_201_p6 = axi_data_4_fu_396_p5;
        end else begin
            ap_phi_mux_axi_data_7_phi_fu_201_p6 = ap_phi_reg_pp0_iter1_axi_data_7_reg_198;
        end
    end else begin
        ap_phi_mux_axi_data_7_phi_fu_201_p6 = ap_phi_reg_pp0_iter1_axi_data_7_reg_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln664_reg_581 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln664_reg_581 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln664_reg_581 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_out_vresampled_blk_n = stream_out_vresampled_empty_n;
    end else begin
        stream_out_vresampled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln664_reg_581 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_out_vresampled_read = 1'b1;
    end else begin
        stream_out_vresampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_io = ((m_axis_video_TREADY == 1'b0) & (icmp_ln664_reg_581 == 1'd0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((m_axis_video_TREADY == 1'b0) & (icmp_ln664_reg_581 == 1'd0)) | ((icmp_ln664_reg_581 == 1'd0) & (stream_out_vresampled_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_365 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln664_reg_581 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_axi_data_11_reg_209 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_15_reg_220 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_19_reg_231 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_23_reg_242 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_2_reg_187 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_7_reg_198 = 'bx;

assign axi_data_10_fu_409_p5 = {{ap_phi_mux_axi_data_7_phi_fu_201_p6[47:24]}, {pix_422_fu_299_p4}, {ap_phi_mux_axi_data_7_phi_fu_201_p6[15:0]}};

assign axi_data_12_fu_474_p5 = {{ap_phi_mux_axi_data_11_phi_fu_212_p6[47:32]}, {pix_444_2_fu_319_p4}, {ap_phi_mux_axi_data_11_phi_fu_212_p6[23:0]}};

assign axi_data_13_fu_461_p5 = {{ap_phi_mux_axi_data_11_phi_fu_212_p6[47:32]}, {pix_444_2_fu_319_p4}, {ap_phi_mux_axi_data_11_phi_fu_212_p6[23:0]}};

assign axi_data_14_fu_448_p5 = {{ap_phi_mux_axi_data_11_phi_fu_212_p6[47:32]}, {pix_rgb_fu_309_p4}, {ap_phi_mux_axi_data_11_phi_fu_212_p6[23:0]}};

assign axi_data_16_fu_513_p5 = {{ap_phi_mux_axi_data_15_phi_fu_223_p6[47:40]}, {pix_444_3_fu_329_p4}, {ap_phi_mux_axi_data_15_phi_fu_223_p6[31:0]}};

assign axi_data_17_fu_500_p5 = {{ap_phi_mux_axi_data_15_phi_fu_223_p6[47:40]}, {pix_444_3_fu_329_p4}, {ap_phi_mux_axi_data_15_phi_fu_223_p6[31:0]}};

assign axi_data_18_fu_487_p5 = {{ap_phi_mux_axi_data_15_phi_fu_223_p6[47:40]}, {pix_444_2_fu_319_p4}, {ap_phi_mux_axi_data_15_phi_fu_223_p6[31:0]}};

assign axi_data_1_fu_348_p3 = {{1'd1}, {pix_444_fu_289_p4}};

assign axi_data_20_fu_552_p5 = {{pix_422_fu_299_p4}, {ap_phi_mux_axi_data_19_phi_fu_234_p6[39:0]}};

assign axi_data_21_fu_539_p5 = {{pix_rgb_fu_309_p4}, {ap_phi_mux_axi_data_19_phi_fu_234_p6[39:0]}};

assign axi_data_22_fu_526_p5 = {{pix_444_3_fu_329_p4}, {ap_phi_mux_axi_data_19_phi_fu_234_p6[39:0]}};

assign axi_data_3_fu_339_p3 = {{1'd1}, {pix_rgb_3_fu_285_p1}};

assign axi_data_4_fu_396_p5 = {{sext_ln618_fu_366_p1[47:16]}, {pix_444_fu_289_p4}, {sext_ln618_fu_366_p1[7:0]}};

assign axi_data_5_fu_383_p5 = {{sext_ln618_fu_366_p1[47:16]}, {pix_422_fu_299_p4}, {sext_ln618_fu_366_p1[7:0]}};

assign axi_data_6_fu_370_p5 = {{sext_ln618_fu_366_p1[47:16]}, {pix_444_fu_289_p4}, {sext_ln618_fu_366_p1[7:0]}};

assign axi_data_8_fu_435_p5 = {{ap_phi_mux_axi_data_7_phi_fu_201_p6[47:24]}, {pix_rgb_fu_309_p4}, {ap_phi_mux_axi_data_7_phi_fu_201_p6[15:0]}};

assign axi_data_9_fu_422_p5 = {{ap_phi_mux_axi_data_7_phi_fu_201_p6[47:24]}, {pix_rgb_3_fu_285_p1}, {ap_phi_mux_axi_data_7_phi_fu_201_p6[15:0]}};

assign axi_data_fu_357_p3 = {{1'd1}, {pix_rgb_3_fu_285_p1}};

assign axi_last_fu_274_p2 = ((ap_sig_allocacmp_j_1 == sub) ? 1'b1 : 1'b0);

assign icmp_ln664_fu_262_p2 = ((ap_sig_allocacmp_j_1 == div207_cast) ? 1'b1 : 1'b0);

assign j_2_fu_268_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign m_axis_video_TDATA = ap_phi_mux_axi_data_23_phi_fu_245_p6;

assign m_axis_video_TDEST = 'bx;

assign m_axis_video_TID = 'bx;

assign m_axis_video_TKEEP = 6'd63;

assign m_axis_video_TLAST = axi_last_reg_585;

assign m_axis_video_TSTRB = 'bx;

assign m_axis_video_TUSER = sof_2_reg_175;

assign p_read_9_reg_572 = p_read;

assign pix_422_fu_299_p4 = {{stream_out_vresampled_dout[23:16]}};

assign pix_444_2_fu_319_p4 = {{stream_out_vresampled_dout[39:32]}};

assign pix_444_3_fu_329_p4 = {{stream_out_vresampled_dout[47:40]}};

assign pix_444_fu_289_p4 = {{stream_out_vresampled_dout[15:8]}};

assign pix_rgb_3_fu_285_p1 = stream_out_vresampled_dout[7:0];

assign pix_rgb_fu_309_p4 = {{stream_out_vresampled_dout[31:24]}};

assign sext_ln618_fu_366_p1 = $signed(ap_phi_mux_axi_data_2_phi_fu_190_p6);

endmodule //bd_2d50_csc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_664_2
