// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_2d50_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_hresampled_dout,
        stream_in_hresampled_num_data_valid,
        stream_in_hresampled_fifo_cap,
        stream_in_hresampled_empty_n,
        stream_in_hresampled_read,
        stream_csc_din,
        stream_csc_num_data_valid,
        stream_csc_fifo_cap,
        stream_csc_full_n,
        stream_csc_write,
        loopWidth_1,
        offsetR,
        K12_load_cast,
        K13_load_cast,
        K11_load_cast,
        offsetG,
        K22_load_cast,
        K23_load_cast,
        K21_load_cast,
        offsetB,
        K32_load_cast,
        K33_load_cast,
        K31_load_cast,
        zext_ln134_1,
        zext_ln134,
        ClipMax_read,
        ClampMin_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] stream_in_hresampled_dout;
input  [4:0] stream_in_hresampled_num_data_valid;
input  [4:0] stream_in_hresampled_fifo_cap;
input   stream_in_hresampled_empty_n;
output   stream_in_hresampled_read;
output  [47:0] stream_csc_din;
input  [4:0] stream_csc_num_data_valid;
input  [4:0] stream_csc_fifo_cap;
input   stream_csc_full_n;
output   stream_csc_write;
input  [10:0] loopWidth_1;
input  [21:0] offsetR;
input  [15:0] K12_load_cast;
input  [15:0] K13_load_cast;
input  [15:0] K11_load_cast;
input  [21:0] offsetG;
input  [15:0] K22_load_cast;
input  [15:0] K23_load_cast;
input  [15:0] K21_load_cast;
input  [21:0] offsetB;
input  [15:0] K32_load_cast;
input  [15:0] K33_load_cast;
input  [15:0] K31_load_cast;
input  [7:0] zext_ln134_1;
input  [7:0] zext_ln134;
input  [7:0] ClipMax_read;
input  [7:0] ClampMin_read;

reg ap_idle;
reg stream_in_hresampled_read;
reg stream_csc_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln136_fu_287_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_hresampled_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_csc_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [13:0] zext_ln134_cast_fu_231_p1;
reg   [13:0] zext_ln134_cast_reg_1106;
wire   [13:0] zext_ln134_1_cast_fu_235_p1;
reg   [13:0] zext_ln134_1_cast_reg_1116;
wire  signed [23:0] K31_load_cast_cast_fu_239_p1;
reg  signed [23:0] K31_load_cast_cast_reg_1126;
wire  signed [23:0] K33_load_cast_cast_fu_243_p1;
reg  signed [23:0] K33_load_cast_cast_reg_1132;
wire  signed [23:0] K32_load_cast_cast_fu_247_p1;
reg  signed [23:0] K32_load_cast_cast_reg_1138;
wire  signed [23:0] K21_load_cast_cast_fu_251_p1;
reg  signed [23:0] K21_load_cast_cast_reg_1144;
wire  signed [23:0] K23_load_cast_cast_fu_255_p1;
reg  signed [23:0] K23_load_cast_cast_reg_1150;
wire  signed [23:0] K22_load_cast_cast_fu_259_p1;
reg  signed [23:0] K22_load_cast_cast_reg_1156;
wire  signed [23:0] K11_load_cast_cast_fu_263_p1;
reg  signed [23:0] K11_load_cast_cast_reg_1162;
wire  signed [23:0] K13_load_cast_cast_fu_267_p1;
reg  signed [23:0] K13_load_cast_cast_reg_1168;
wire  signed [23:0] K12_load_cast_cast_fu_271_p1;
reg  signed [23:0] K12_load_cast_cast_reg_1174;
wire   [7:0] Rpix_fu_304_p1;
reg   [7:0] Rpix_reg_1184;
reg   [7:0] Rpix_reg_1184_pp0_iter2_reg;
reg   [7:0] Bpix_reg_1189;
reg   [7:0] Bpix_reg_1189_pp0_iter2_reg;
wire   [23:0] zext_ln106_1_fu_328_p1;
wire   [23:0] zext_ln106_2_fu_342_p1;
reg   [7:0] tmp_2_reg_1208;
reg   [7:0] tmp_2_reg_1208_pp0_iter2_reg;
reg   [7:0] tmp_3_reg_1213;
reg   [7:0] tmp_3_reg_1213_pp0_iter2_reg;
wire  signed [24:0] sext_ln192_fu_377_p1;
wire   [24:0] add_ln192_1_fu_405_p2;
reg   [24:0] add_ln192_1_reg_1224;
wire   [19:0] trunc_ln192_1_fu_411_p1;
reg   [19:0] trunc_ln192_1_reg_1229;
wire  signed [24:0] sext_ln194_fu_420_p1;
wire   [24:0] add_ln194_1_fu_448_p2;
reg   [24:0] add_ln194_1_reg_1240;
wire   [19:0] trunc_ln194_1_fu_454_p1;
reg   [19:0] trunc_ln194_1_reg_1245;
wire  signed [24:0] sext_ln196_fu_463_p1;
wire   [24:0] add_ln196_1_fu_491_p2;
reg   [24:0] add_ln196_1_reg_1256;
wire   [19:0] trunc_ln196_1_fu_497_p1;
reg   [19:0] trunc_ln196_1_reg_1261;
wire   [24:0] add_ln192_4_fu_531_p2;
reg   [24:0] add_ln192_4_reg_1266;
wire   [19:0] trunc_ln192_3_fu_537_p1;
reg   [19:0] trunc_ln192_3_reg_1271;
wire   [24:0] add_ln194_4_fu_565_p2;
reg   [24:0] add_ln194_4_reg_1276;
wire   [19:0] trunc_ln194_3_fu_571_p1;
reg   [19:0] trunc_ln194_3_reg_1281;
wire   [24:0] add_ln196_4_fu_599_p2;
reg   [24:0] add_ln196_4_reg_1286;
wire   [19:0] trunc_ln196_3_fu_605_p1;
reg   [19:0] trunc_ln196_3_reg_1291;
reg   [11:0] x_fu_112;
wire   [11:0] x_7_fu_293_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_x_6;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] loopWidth_1_cast_fu_275_p1;
wire   [7:0] Gpix_fu_308_p4;
wire   [7:0] tmp_fu_332_p4;
wire   [21:0] or_ln192_fu_372_p2;
wire   [7:0] mul_ln192_1_fu_381_p0;
wire   [23:0] zext_ln140_fu_366_p1;
wire  signed [15:0] mul_ln192_1_fu_381_p1;
wire  signed [23:0] mul_ln192_1_fu_381_p2;
wire  signed [15:0] mul_ln192_2_fu_390_p0;
wire   [7:0] mul_ln192_2_fu_390_p1;
wire   [23:0] zext_ln106_fu_369_p1;
wire  signed [23:0] mul_ln192_2_fu_390_p2;
wire  signed [24:0] sext_ln192_3_fu_395_p1;
wire  signed [24:0] sext_ln192_2_fu_386_p1;
wire   [23:0] add_ln192_8_fu_399_p2;
wire   [21:0] or_ln194_fu_415_p2;
wire   [7:0] mul_ln194_1_fu_424_p0;
wire  signed [15:0] mul_ln194_1_fu_424_p1;
wire  signed [23:0] mul_ln194_1_fu_424_p2;
wire  signed [15:0] mul_ln194_2_fu_433_p0;
wire   [7:0] mul_ln194_2_fu_433_p1;
wire  signed [23:0] mul_ln194_2_fu_433_p2;
wire  signed [24:0] sext_ln194_3_fu_438_p1;
wire  signed [24:0] sext_ln194_2_fu_429_p1;
wire   [23:0] add_ln194_8_fu_442_p2;
wire   [21:0] or_ln196_fu_458_p2;
wire   [7:0] mul_ln196_1_fu_467_p0;
wire  signed [15:0] mul_ln196_1_fu_467_p1;
wire  signed [23:0] mul_ln196_1_fu_467_p2;
wire  signed [15:0] mul_ln196_2_fu_476_p0;
wire   [7:0] mul_ln196_2_fu_476_p1;
wire  signed [23:0] mul_ln196_2_fu_476_p2;
wire  signed [24:0] sext_ln196_3_fu_481_p1;
wire  signed [24:0] sext_ln196_2_fu_472_p1;
wire   [23:0] add_ln196_8_fu_485_p2;
wire   [7:0] mul_ln192_3_fu_507_p0;
wire   [23:0] zext_ln106_3_fu_501_p1;
wire  signed [15:0] mul_ln192_3_fu_507_p1;
wire  signed [23:0] mul_ln192_3_fu_507_p2;
wire   [7:0] mul_ln192_4_fu_516_p0;
wire   [23:0] zext_ln106_4_fu_504_p1;
wire  signed [15:0] mul_ln192_4_fu_516_p1;
wire  signed [23:0] mul_ln192_4_fu_516_p2;
wire  signed [24:0] sext_ln192_6_fu_512_p1;
wire  signed [24:0] sext_ln192_9_fu_521_p1;
wire   [23:0] add_ln192_9_fu_525_p2;
wire   [7:0] mul_ln194_3_fu_541_p0;
wire  signed [15:0] mul_ln194_3_fu_541_p1;
wire  signed [23:0] mul_ln194_3_fu_541_p2;
wire   [7:0] mul_ln194_4_fu_550_p0;
wire  signed [15:0] mul_ln194_4_fu_550_p1;
wire  signed [23:0] mul_ln194_4_fu_550_p2;
wire  signed [24:0] sext_ln194_6_fu_546_p1;
wire  signed [24:0] sext_ln194_9_fu_555_p1;
wire   [23:0] add_ln194_9_fu_559_p2;
wire   [7:0] mul_ln196_3_fu_575_p0;
wire  signed [15:0] mul_ln196_3_fu_575_p1;
wire  signed [23:0] mul_ln196_3_fu_575_p2;
wire   [7:0] mul_ln196_4_fu_584_p0;
wire  signed [15:0] mul_ln196_4_fu_584_p1;
wire  signed [23:0] mul_ln196_4_fu_584_p2;
wire  signed [24:0] sext_ln196_6_fu_580_p1;
wire  signed [24:0] sext_ln196_9_fu_589_p1;
wire   [23:0] add_ln196_9_fu_593_p2;
wire  signed [24:0] grp_fu_1010_p3;
wire   [19:0] trunc_ln192_fu_609_p1;
wire  signed [25:0] sext_ln192_5_fu_615_p1;
wire  signed [25:0] sext_ln192_4_fu_612_p1;
wire   [25:0] add_ln192_2_fu_623_p2;
wire  signed [24:0] grp_fu_1019_p3;
wire   [19:0] trunc_ln194_fu_639_p1;
wire  signed [25:0] sext_ln194_5_fu_645_p1;
wire  signed [25:0] sext_ln194_4_fu_642_p1;
wire   [25:0] add_ln194_2_fu_653_p2;
wire  signed [24:0] grp_fu_1028_p3;
wire   [19:0] trunc_ln196_fu_669_p1;
wire  signed [25:0] sext_ln196_5_fu_675_p1;
wire  signed [25:0] sext_ln196_4_fu_672_p1;
wire   [25:0] add_ln196_2_fu_683_p2;
wire   [13:0] Rres_fu_629_p4;
wire   [19:0] add_ln192_6_fu_618_p2;
wire   [0:0] icmp_ln198_1_fu_704_p2;
wire   [7:0] trunc_ln_fu_709_p4;
wire   [0:0] icmp_ln198_fu_699_p2;
wire   [7:0] select_ln198_fu_719_p3;
wire   [13:0] Gres_fu_659_p4;
wire   [19:0] add_ln194_6_fu_648_p2;
wire   [13:0] Bres_fu_689_p4;
wire   [19:0] add_ln196_6_fu_678_p2;
wire   [0:0] icmp_ln200_1_fu_758_p2;
wire   [7:0] trunc_ln4_fu_763_p4;
wire   [0:0] icmp_ln200_fu_753_p2;
wire   [7:0] select_ln200_fu_773_p3;
wire  signed [24:0] grp_fu_1037_p3;
wire   [19:0] trunc_ln192_2_fu_787_p1;
wire  signed [25:0] sext_ln192_10_fu_793_p1;
wire  signed [25:0] sext_ln192_8_fu_790_p1;
wire   [25:0] add_ln192_5_fu_801_p2;
wire  signed [24:0] grp_fu_1046_p3;
wire   [19:0] trunc_ln194_2_fu_817_p1;
wire  signed [25:0] sext_ln194_10_fu_823_p1;
wire  signed [25:0] sext_ln194_8_fu_820_p1;
wire   [25:0] add_ln194_5_fu_831_p2;
wire  signed [24:0] grp_fu_1055_p3;
wire   [19:0] trunc_ln196_2_fu_847_p1;
wire  signed [25:0] sext_ln196_10_fu_853_p1;
wire  signed [25:0] sext_ln196_8_fu_850_p1;
wire   [25:0] add_ln196_5_fu_861_p2;
wire   [13:0] Rres_1_fu_807_p4;
wire   [19:0] add_ln192_7_fu_796_p2;
wire   [0:0] icmp_ln198_3_fu_882_p2;
wire   [7:0] trunc_ln198_1_fu_887_p4;
wire   [0:0] icmp_ln198_2_fu_877_p2;
wire   [7:0] select_ln198_2_fu_897_p3;
wire   [13:0] Gres_1_fu_837_p4;
wire   [19:0] add_ln194_7_fu_826_p2;
wire   [0:0] icmp_ln199_3_fu_916_p2;
wire   [7:0] trunc_ln199_1_fu_921_p4;
wire   [0:0] icmp_ln199_2_fu_911_p2;
wire   [7:0] select_ln199_fu_931_p3;
wire   [13:0] Bres_1_fu_867_p4;
wire   [19:0] add_ln196_7_fu_856_p2;
wire   [0:0] icmp_ln200_3_fu_950_p2;
wire   [7:0] trunc_ln200_1_fu_955_p4;
wire   [0:0] icmp_ln200_2_fu_945_p2;
wire   [7:0] select_ln200_2_fu_965_p3;
wire   [0:0] icmp_ln199_1_fu_738_p2;
wire   [7:0] trunc_ln3_fu_743_p4;
wire   [0:0] icmp_ln199_fu_733_p2;
wire   [7:0] select_ln199_2_fu_979_p3;
wire   [7:0] select_ln200_3_fu_972_p3;
wire   [7:0] select_ln199_1_fu_938_p3;
wire   [7:0] select_ln198_3_fu_904_p3;
wire   [7:0] select_ln200_1_fu_780_p3;
wire   [7:0] select_ln199_3_fu_986_p3;
wire   [7:0] select_ln198_1_fu_726_p3;
wire   [7:0] grp_fu_1010_p0;
wire  signed [15:0] grp_fu_1010_p1;
wire  signed [21:0] grp_fu_1010_p2;
wire   [7:0] grp_fu_1019_p0;
wire  signed [15:0] grp_fu_1019_p1;
wire  signed [21:0] grp_fu_1019_p2;
wire   [7:0] grp_fu_1028_p0;
wire  signed [15:0] grp_fu_1028_p1;
wire  signed [21:0] grp_fu_1028_p2;
wire   [7:0] grp_fu_1037_p0;
wire  signed [15:0] grp_fu_1037_p1;
wire  signed [21:0] grp_fu_1037_p2;
wire   [7:0] grp_fu_1046_p0;
wire  signed [15:0] grp_fu_1046_p1;
wire  signed [21:0] grp_fu_1046_p2;
wire   [7:0] grp_fu_1055_p0;
wire  signed [15:0] grp_fu_1055_p1;
wire  signed [21:0] grp_fu_1055_p2;
reg    grp_fu_1010_ce;
reg    grp_fu_1019_ce;
reg    grp_fu_1028_ce;
reg    grp_fu_1037_ce;
reg    grp_fu_1046_ce;
reg    grp_fu_1055_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 x_fu_112 = 12'd0;
#0 ap_done_reg = 1'b0;
end

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U151(
    .din0(mul_ln192_1_fu_381_p0),
    .din1(mul_ln192_1_fu_381_p1),
    .dout(mul_ln192_1_fu_381_p2)
);

bd_2d50_csc_0_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U152(
    .din0(mul_ln192_2_fu_390_p0),
    .din1(mul_ln192_2_fu_390_p1),
    .dout(mul_ln192_2_fu_390_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U153(
    .din0(mul_ln194_1_fu_424_p0),
    .din1(mul_ln194_1_fu_424_p1),
    .dout(mul_ln194_1_fu_424_p2)
);

bd_2d50_csc_0_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U154(
    .din0(mul_ln194_2_fu_433_p0),
    .din1(mul_ln194_2_fu_433_p1),
    .dout(mul_ln194_2_fu_433_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U155(
    .din0(mul_ln196_1_fu_467_p0),
    .din1(mul_ln196_1_fu_467_p1),
    .dout(mul_ln196_1_fu_467_p2)
);

bd_2d50_csc_0_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U156(
    .din0(mul_ln196_2_fu_476_p0),
    .din1(mul_ln196_2_fu_476_p1),
    .dout(mul_ln196_2_fu_476_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U157(
    .din0(mul_ln192_3_fu_507_p0),
    .din1(mul_ln192_3_fu_507_p1),
    .dout(mul_ln192_3_fu_507_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U158(
    .din0(mul_ln192_4_fu_516_p0),
    .din1(mul_ln192_4_fu_516_p1),
    .dout(mul_ln192_4_fu_516_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U159(
    .din0(mul_ln194_3_fu_541_p0),
    .din1(mul_ln194_3_fu_541_p1),
    .dout(mul_ln194_3_fu_541_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U160(
    .din0(mul_ln194_4_fu_550_p0),
    .din1(mul_ln194_4_fu_550_p1),
    .dout(mul_ln194_4_fu_550_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U161(
    .din0(mul_ln196_3_fu_575_p0),
    .din1(mul_ln196_3_fu_575_p1),
    .dout(mul_ln196_3_fu_575_p2)
);

bd_2d50_csc_0_mul_8ns_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_8ns_16s_24_1_1_U162(
    .din0(mul_ln196_4_fu_584_p0),
    .din1(mul_ln196_4_fu_584_p1),
    .dout(mul_ln196_4_fu_584_p2)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U163(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1010_p0),
    .din1(grp_fu_1010_p1),
    .din2(grp_fu_1010_p2),
    .ce(grp_fu_1010_ce),
    .dout(grp_fu_1010_p3)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U164(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1019_p0),
    .din1(grp_fu_1019_p1),
    .din2(grp_fu_1019_p2),
    .ce(grp_fu_1019_ce),
    .dout(grp_fu_1019_p3)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U165(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1028_p0),
    .din1(grp_fu_1028_p1),
    .din2(grp_fu_1028_p2),
    .ce(grp_fu_1028_ce),
    .dout(grp_fu_1028_p3)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U166(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1037_p0),
    .din1(grp_fu_1037_p1),
    .din2(grp_fu_1037_p2),
    .ce(grp_fu_1037_ce),
    .dout(grp_fu_1037_p3)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U167(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1046_p0),
    .din1(grp_fu_1046_p1),
    .din2(grp_fu_1046_p2),
    .ce(grp_fu_1046_ce),
    .dout(grp_fu_1046_p3)
);

bd_2d50_csc_0_mac_muladd_8ns_16s_22s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_22s_25_4_1_U168(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1055_p0),
    .din1(grp_fu_1055_p1),
    .din2(grp_fu_1055_p2),
    .ce(grp_fu_1055_ce),
    .dout(grp_fu_1055_p3)
);

bd_2d50_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln136_fu_287_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_112 <= x_7_fu_293_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_112 <= 12'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Bpix_reg_1189 <= {{stream_in_hresampled_dout[23:16]}};
        K11_load_cast_cast_reg_1162 <= K11_load_cast_cast_fu_263_p1;
        K12_load_cast_cast_reg_1174 <= K12_load_cast_cast_fu_271_p1;
        K13_load_cast_cast_reg_1168 <= K13_load_cast_cast_fu_267_p1;
        K21_load_cast_cast_reg_1144 <= K21_load_cast_cast_fu_251_p1;
        K22_load_cast_cast_reg_1156 <= K22_load_cast_cast_fu_259_p1;
        K23_load_cast_cast_reg_1150 <= K23_load_cast_cast_fu_255_p1;
        K31_load_cast_cast_reg_1126 <= K31_load_cast_cast_fu_239_p1;
        K32_load_cast_cast_reg_1138 <= K32_load_cast_cast_fu_247_p1;
        K33_load_cast_cast_reg_1132 <= K33_load_cast_cast_fu_243_p1;
        Rpix_reg_1184 <= Rpix_fu_304_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_2_reg_1208 <= {{stream_in_hresampled_dout[39:32]}};
        tmp_3_reg_1213 <= {{stream_in_hresampled_dout[47:40]}};
        zext_ln134_1_cast_reg_1116[7 : 0] <= zext_ln134_1_cast_fu_235_p1[7 : 0];
        zext_ln134_cast_reg_1106[7 : 0] <= zext_ln134_cast_fu_231_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Bpix_reg_1189_pp0_iter2_reg <= Bpix_reg_1189;
        Rpix_reg_1184_pp0_iter2_reg <= Rpix_reg_1184;
        add_ln192_1_reg_1224 <= add_ln192_1_fu_405_p2;
        add_ln192_4_reg_1266 <= add_ln192_4_fu_531_p2;
        add_ln194_1_reg_1240 <= add_ln194_1_fu_448_p2;
        add_ln194_4_reg_1276 <= add_ln194_4_fu_565_p2;
        add_ln196_1_reg_1256 <= add_ln196_1_fu_491_p2;
        add_ln196_4_reg_1286 <= add_ln196_4_fu_599_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        tmp_2_reg_1208_pp0_iter2_reg <= tmp_2_reg_1208;
        tmp_3_reg_1213_pp0_iter2_reg <= tmp_3_reg_1213;
        trunc_ln192_1_reg_1229 <= trunc_ln192_1_fu_411_p1;
        trunc_ln192_3_reg_1271 <= trunc_ln192_3_fu_537_p1;
        trunc_ln194_1_reg_1245 <= trunc_ln194_1_fu_454_p1;
        trunc_ln194_3_reg_1281 <= trunc_ln194_3_fu_571_p1;
        trunc_ln196_1_reg_1261 <= trunc_ln196_1_fu_497_p1;
        trunc_ln196_3_reg_1291 <= trunc_ln196_3_fu_605_p1;
    end
end

always @ (*) begin
    if (((icmp_ln136_fu_287_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_6 = 12'd1;
    end else begin
        ap_sig_allocacmp_x_6 = x_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1010_ce = 1'b1;
    end else begin
        grp_fu_1010_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1019_ce = 1'b1;
    end else begin
        grp_fu_1019_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1028_ce = 1'b1;
    end else begin
        grp_fu_1028_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1037_ce = 1'b1;
    end else begin
        grp_fu_1037_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1046_ce = 1'b1;
    end else begin
        grp_fu_1046_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1055_ce = 1'b1;
    end else begin
        grp_fu_1055_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stream_csc_blk_n = stream_csc_full_n;
    end else begin
        stream_csc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        stream_csc_write = 1'b1;
    end else begin
        stream_csc_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_hresampled_blk_n = stream_in_hresampled_empty_n;
    end else begin
        stream_in_hresampled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_hresampled_read = 1'b1;
    end else begin
        stream_in_hresampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Bres_1_fu_867_p4 = {{add_ln196_5_fu_861_p2[25:12]}};

assign Bres_fu_689_p4 = {{add_ln196_2_fu_683_p2[25:12]}};

assign Gpix_fu_308_p4 = {{stream_in_hresampled_dout[15:8]}};

assign Gres_1_fu_837_p4 = {{add_ln194_5_fu_831_p2[25:12]}};

assign Gres_fu_659_p4 = {{add_ln194_2_fu_653_p2[25:12]}};

assign K11_load_cast_cast_fu_263_p1 = $signed(K11_load_cast);

assign K12_load_cast_cast_fu_271_p1 = $signed(K12_load_cast);

assign K13_load_cast_cast_fu_267_p1 = $signed(K13_load_cast);

assign K21_load_cast_cast_fu_251_p1 = $signed(K21_load_cast);

assign K22_load_cast_cast_fu_259_p1 = $signed(K22_load_cast);

assign K23_load_cast_cast_fu_255_p1 = $signed(K23_load_cast);

assign K31_load_cast_cast_fu_239_p1 = $signed(K31_load_cast);

assign K32_load_cast_cast_fu_247_p1 = $signed(K32_load_cast);

assign K33_load_cast_cast_fu_243_p1 = $signed(K33_load_cast);

assign Rpix_fu_304_p1 = stream_in_hresampled_dout[7:0];

assign Rres_1_fu_807_p4 = {{add_ln192_5_fu_801_p2[25:12]}};

assign Rres_fu_629_p4 = {{add_ln192_2_fu_623_p2[25:12]}};

assign add_ln192_1_fu_405_p2 = ($signed(sext_ln192_3_fu_395_p1) + $signed(sext_ln192_2_fu_386_p1));

assign add_ln192_2_fu_623_p2 = ($signed(sext_ln192_5_fu_615_p1) + $signed(sext_ln192_4_fu_612_p1));

assign add_ln192_4_fu_531_p2 = ($signed(sext_ln192_6_fu_512_p1) + $signed(sext_ln192_9_fu_521_p1));

assign add_ln192_5_fu_801_p2 = ($signed(sext_ln192_10_fu_793_p1) + $signed(sext_ln192_8_fu_790_p1));

assign add_ln192_6_fu_618_p2 = (trunc_ln192_1_reg_1229 + trunc_ln192_fu_609_p1);

assign add_ln192_7_fu_796_p2 = (trunc_ln192_3_reg_1271 + trunc_ln192_2_fu_787_p1);

assign add_ln192_8_fu_399_p2 = ($signed(mul_ln192_2_fu_390_p2) + $signed(mul_ln192_1_fu_381_p2));

assign add_ln192_9_fu_525_p2 = ($signed(mul_ln192_3_fu_507_p2) + $signed(mul_ln192_4_fu_516_p2));

assign add_ln194_1_fu_448_p2 = ($signed(sext_ln194_3_fu_438_p1) + $signed(sext_ln194_2_fu_429_p1));

assign add_ln194_2_fu_653_p2 = ($signed(sext_ln194_5_fu_645_p1) + $signed(sext_ln194_4_fu_642_p1));

assign add_ln194_4_fu_565_p2 = ($signed(sext_ln194_6_fu_546_p1) + $signed(sext_ln194_9_fu_555_p1));

assign add_ln194_5_fu_831_p2 = ($signed(sext_ln194_10_fu_823_p1) + $signed(sext_ln194_8_fu_820_p1));

assign add_ln194_6_fu_648_p2 = (trunc_ln194_1_reg_1245 + trunc_ln194_fu_639_p1);

assign add_ln194_7_fu_826_p2 = (trunc_ln194_3_reg_1281 + trunc_ln194_2_fu_817_p1);

assign add_ln194_8_fu_442_p2 = ($signed(mul_ln194_2_fu_433_p2) + $signed(mul_ln194_1_fu_424_p2));

assign add_ln194_9_fu_559_p2 = ($signed(mul_ln194_3_fu_541_p2) + $signed(mul_ln194_4_fu_550_p2));

assign add_ln196_1_fu_491_p2 = ($signed(sext_ln196_3_fu_481_p1) + $signed(sext_ln196_2_fu_472_p1));

assign add_ln196_2_fu_683_p2 = ($signed(sext_ln196_5_fu_675_p1) + $signed(sext_ln196_4_fu_672_p1));

assign add_ln196_4_fu_599_p2 = ($signed(sext_ln196_6_fu_580_p1) + $signed(sext_ln196_9_fu_589_p1));

assign add_ln196_5_fu_861_p2 = ($signed(sext_ln196_10_fu_853_p1) + $signed(sext_ln196_8_fu_850_p1));

assign add_ln196_6_fu_678_p2 = (trunc_ln196_1_reg_1261 + trunc_ln196_fu_669_p1);

assign add_ln196_7_fu_856_p2 = (trunc_ln196_3_reg_1291 + trunc_ln196_2_fu_847_p1);

assign add_ln196_8_fu_485_p2 = ($signed(mul_ln196_2_fu_476_p2) + $signed(mul_ln196_1_fu_467_p2));

assign add_ln196_9_fu_593_p2 = ($signed(mul_ln196_3_fu_575_p2) + $signed(mul_ln196_4_fu_584_p2));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (stream_in_hresampled_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (stream_csc_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1010_p0 = zext_ln106_1_fu_328_p1;

assign grp_fu_1010_p1 = K12_load_cast_cast_reg_1174;

assign grp_fu_1010_p2 = sext_ln192_fu_377_p1;

assign grp_fu_1019_p0 = zext_ln106_1_fu_328_p1;

assign grp_fu_1019_p1 = K22_load_cast_cast_reg_1156;

assign grp_fu_1019_p2 = sext_ln194_fu_420_p1;

assign grp_fu_1028_p0 = zext_ln106_1_fu_328_p1;

assign grp_fu_1028_p1 = K32_load_cast_cast_reg_1138;

assign grp_fu_1028_p2 = sext_ln196_fu_463_p1;

assign grp_fu_1037_p0 = zext_ln106_2_fu_342_p1;

assign grp_fu_1037_p1 = K11_load_cast_cast_reg_1162;

assign grp_fu_1037_p2 = sext_ln192_fu_377_p1;

assign grp_fu_1046_p0 = zext_ln106_2_fu_342_p1;

assign grp_fu_1046_p1 = K21_load_cast_cast_reg_1144;

assign grp_fu_1046_p2 = sext_ln194_fu_420_p1;

assign grp_fu_1055_p0 = zext_ln106_2_fu_342_p1;

assign grp_fu_1055_p1 = K31_load_cast_cast_reg_1126;

assign grp_fu_1055_p2 = sext_ln196_fu_463_p1;

assign icmp_ln136_fu_287_p2 = ((ap_sig_allocacmp_x_6 > loopWidth_1_cast_fu_275_p1) ? 1'b1 : 1'b0);

assign icmp_ln198_1_fu_704_p2 = (($signed(Rres_fu_629_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln198_2_fu_877_p2 = (($signed(Rres_1_fu_807_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign icmp_ln198_3_fu_882_p2 = (($signed(Rres_1_fu_807_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_699_p2 = (($signed(Rres_fu_629_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign icmp_ln199_1_fu_738_p2 = (($signed(Gres_fu_659_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln199_2_fu_911_p2 = (($signed(Gres_1_fu_837_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign icmp_ln199_3_fu_916_p2 = (($signed(Gres_1_fu_837_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_733_p2 = (($signed(Gres_fu_659_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign icmp_ln200_1_fu_758_p2 = (($signed(Bres_fu_689_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln200_2_fu_945_p2 = (($signed(Bres_1_fu_867_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign icmp_ln200_3_fu_950_p2 = (($signed(Bres_1_fu_867_p4) > $signed(zext_ln134_cast_reg_1106)) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_753_p2 = (($signed(Bres_fu_689_p4) < $signed(zext_ln134_1_cast_reg_1116)) ? 1'b1 : 1'b0);

assign loopWidth_1_cast_fu_275_p1 = loopWidth_1;

assign mul_ln192_1_fu_381_p0 = zext_ln140_fu_366_p1;

assign mul_ln192_1_fu_381_p1 = K13_load_cast_cast_reg_1168;

assign mul_ln192_2_fu_390_p0 = K11_load_cast_cast_reg_1162;

assign mul_ln192_2_fu_390_p1 = zext_ln106_fu_369_p1;

assign mul_ln192_3_fu_507_p0 = zext_ln106_3_fu_501_p1;

assign mul_ln192_3_fu_507_p1 = K12_load_cast_cast_reg_1174;

assign mul_ln192_4_fu_516_p0 = zext_ln106_4_fu_504_p1;

assign mul_ln192_4_fu_516_p1 = K13_load_cast_cast_reg_1168;

assign mul_ln194_1_fu_424_p0 = zext_ln140_fu_366_p1;

assign mul_ln194_1_fu_424_p1 = K23_load_cast_cast_reg_1150;

assign mul_ln194_2_fu_433_p0 = K21_load_cast_cast_reg_1144;

assign mul_ln194_2_fu_433_p1 = zext_ln106_fu_369_p1;

assign mul_ln194_3_fu_541_p0 = zext_ln106_3_fu_501_p1;

assign mul_ln194_3_fu_541_p1 = K22_load_cast_cast_reg_1156;

assign mul_ln194_4_fu_550_p0 = zext_ln106_4_fu_504_p1;

assign mul_ln194_4_fu_550_p1 = K23_load_cast_cast_reg_1150;

assign mul_ln196_1_fu_467_p0 = zext_ln140_fu_366_p1;

assign mul_ln196_1_fu_467_p1 = K33_load_cast_cast_reg_1132;

assign mul_ln196_2_fu_476_p0 = K31_load_cast_cast_reg_1126;

assign mul_ln196_2_fu_476_p1 = zext_ln106_fu_369_p1;

assign mul_ln196_3_fu_575_p0 = zext_ln106_3_fu_501_p1;

assign mul_ln196_3_fu_575_p1 = K32_load_cast_cast_reg_1138;

assign mul_ln196_4_fu_584_p0 = zext_ln106_4_fu_504_p1;

assign mul_ln196_4_fu_584_p1 = K33_load_cast_cast_reg_1132;

assign or_ln192_fu_372_p2 = (offsetR | 22'd2048);

assign or_ln194_fu_415_p2 = (offsetG | 22'd2048);

assign or_ln196_fu_458_p2 = (offsetB | 22'd2048);

assign select_ln198_1_fu_726_p3 = ((icmp_ln198_fu_699_p2[0:0] == 1'b1) ? ClampMin_read : select_ln198_fu_719_p3);

assign select_ln198_2_fu_897_p3 = ((icmp_ln198_3_fu_882_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln198_1_fu_887_p4);

assign select_ln198_3_fu_904_p3 = ((icmp_ln198_2_fu_877_p2[0:0] == 1'b1) ? ClampMin_read : select_ln198_2_fu_897_p3);

assign select_ln198_fu_719_p3 = ((icmp_ln198_1_fu_704_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln_fu_709_p4);

assign select_ln199_1_fu_938_p3 = ((icmp_ln199_2_fu_911_p2[0:0] == 1'b1) ? ClampMin_read : select_ln199_fu_931_p3);

assign select_ln199_2_fu_979_p3 = ((icmp_ln199_1_fu_738_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln3_fu_743_p4);

assign select_ln199_3_fu_986_p3 = ((icmp_ln199_fu_733_p2[0:0] == 1'b1) ? ClampMin_read : select_ln199_2_fu_979_p3);

assign select_ln199_fu_931_p3 = ((icmp_ln199_3_fu_916_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln199_1_fu_921_p4);

assign select_ln200_1_fu_780_p3 = ((icmp_ln200_fu_753_p2[0:0] == 1'b1) ? ClampMin_read : select_ln200_fu_773_p3);

assign select_ln200_2_fu_965_p3 = ((icmp_ln200_3_fu_950_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln200_1_fu_955_p4);

assign select_ln200_3_fu_972_p3 = ((icmp_ln200_2_fu_945_p2[0:0] == 1'b1) ? ClampMin_read : select_ln200_2_fu_965_p3);

assign select_ln200_fu_773_p3 = ((icmp_ln200_1_fu_758_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln4_fu_763_p4);

assign sext_ln192_10_fu_793_p1 = $signed(add_ln192_4_reg_1266);

assign sext_ln192_2_fu_386_p1 = mul_ln192_1_fu_381_p2;

assign sext_ln192_3_fu_395_p1 = mul_ln192_2_fu_390_p2;

assign sext_ln192_4_fu_612_p1 = grp_fu_1010_p3;

assign sext_ln192_5_fu_615_p1 = $signed(add_ln192_1_reg_1224);

assign sext_ln192_6_fu_512_p1 = mul_ln192_3_fu_507_p2;

assign sext_ln192_8_fu_790_p1 = grp_fu_1037_p3;

assign sext_ln192_9_fu_521_p1 = mul_ln192_4_fu_516_p2;

assign sext_ln192_fu_377_p1 = $signed(or_ln192_fu_372_p2);

assign sext_ln194_10_fu_823_p1 = $signed(add_ln194_4_reg_1276);

assign sext_ln194_2_fu_429_p1 = mul_ln194_1_fu_424_p2;

assign sext_ln194_3_fu_438_p1 = mul_ln194_2_fu_433_p2;

assign sext_ln194_4_fu_642_p1 = grp_fu_1019_p3;

assign sext_ln194_5_fu_645_p1 = $signed(add_ln194_1_reg_1240);

assign sext_ln194_6_fu_546_p1 = mul_ln194_3_fu_541_p2;

assign sext_ln194_8_fu_820_p1 = grp_fu_1046_p3;

assign sext_ln194_9_fu_555_p1 = mul_ln194_4_fu_550_p2;

assign sext_ln194_fu_420_p1 = $signed(or_ln194_fu_415_p2);

assign sext_ln196_10_fu_853_p1 = $signed(add_ln196_4_reg_1286);

assign sext_ln196_2_fu_472_p1 = mul_ln196_1_fu_467_p2;

assign sext_ln196_3_fu_481_p1 = mul_ln196_2_fu_476_p2;

assign sext_ln196_4_fu_672_p1 = grp_fu_1028_p3;

assign sext_ln196_5_fu_675_p1 = $signed(add_ln196_1_reg_1256);

assign sext_ln196_6_fu_580_p1 = mul_ln196_3_fu_575_p2;

assign sext_ln196_8_fu_850_p1 = grp_fu_1055_p3;

assign sext_ln196_9_fu_589_p1 = mul_ln196_4_fu_584_p2;

assign sext_ln196_fu_463_p1 = $signed(or_ln196_fu_458_p2);

assign stream_csc_din = {{{{{{select_ln200_3_fu_972_p3}, {select_ln199_1_fu_938_p3}}, {select_ln198_3_fu_904_p3}}, {select_ln200_1_fu_780_p3}}, {select_ln199_3_fu_986_p3}}, {select_ln198_1_fu_726_p3}};

assign tmp_fu_332_p4 = {{stream_in_hresampled_dout[31:24]}};

assign trunc_ln192_1_fu_411_p1 = add_ln192_8_fu_399_p2[19:0];

assign trunc_ln192_2_fu_787_p1 = grp_fu_1037_p3[19:0];

assign trunc_ln192_3_fu_537_p1 = add_ln192_9_fu_525_p2[19:0];

assign trunc_ln192_fu_609_p1 = grp_fu_1010_p3[19:0];

assign trunc_ln194_1_fu_454_p1 = add_ln194_8_fu_442_p2[19:0];

assign trunc_ln194_2_fu_817_p1 = grp_fu_1046_p3[19:0];

assign trunc_ln194_3_fu_571_p1 = add_ln194_9_fu_559_p2[19:0];

assign trunc_ln194_fu_639_p1 = grp_fu_1019_p3[19:0];

assign trunc_ln196_1_fu_497_p1 = add_ln196_8_fu_485_p2[19:0];

assign trunc_ln196_2_fu_847_p1 = grp_fu_1055_p3[19:0];

assign trunc_ln196_3_fu_605_p1 = add_ln196_9_fu_593_p2[19:0];

assign trunc_ln196_fu_669_p1 = grp_fu_1028_p3[19:0];

assign trunc_ln198_1_fu_887_p4 = {{add_ln192_7_fu_796_p2[19:12]}};

assign trunc_ln199_1_fu_921_p4 = {{add_ln194_7_fu_826_p2[19:12]}};

assign trunc_ln200_1_fu_955_p4 = {{add_ln196_7_fu_856_p2[19:12]}};

assign trunc_ln3_fu_743_p4 = {{add_ln194_6_fu_648_p2[19:12]}};

assign trunc_ln4_fu_763_p4 = {{add_ln196_6_fu_678_p2[19:12]}};

assign trunc_ln_fu_709_p4 = {{add_ln192_6_fu_618_p2[19:12]}};

assign x_7_fu_293_p2 = (ap_sig_allocacmp_x_6 + 12'd1);

assign zext_ln106_1_fu_328_p1 = Gpix_fu_308_p4;

assign zext_ln106_2_fu_342_p1 = tmp_fu_332_p4;

assign zext_ln106_3_fu_501_p1 = tmp_2_reg_1208_pp0_iter2_reg;

assign zext_ln106_4_fu_504_p1 = tmp_3_reg_1213_pp0_iter2_reg;

assign zext_ln106_fu_369_p1 = Rpix_reg_1184_pp0_iter2_reg;

assign zext_ln134_1_cast_fu_235_p1 = zext_ln134_1;

assign zext_ln134_cast_fu_231_p1 = zext_ln134;

assign zext_ln140_fu_366_p1 = Bpix_reg_1189_pp0_iter2_reg;

always @ (posedge ap_clk) begin
    zext_ln134_cast_reg_1106[13:8] <= 6'b000000;
    zext_ln134_1_cast_reg_1116[13:8] <= 6'b000000;
end

endmodule //bd_2d50_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2
